INSERT INTO Pet VALUES ('Quincey', 'Hendrika', '2009-04-23', 'F', 'definition', 'project', 'local', 'Sheep');
INSERT INTO Pet VALUES ('Romola', 'Sabine', '2013-07-14', 'F', 'uniform', '24 hour', 'Fully-configurable', 'Fowl');
INSERT INTO Pet VALUES ('Belita', 'Tadio', '2003-04-16', 'M', 'Reduced', 'monitoring', 'analyzer', 'Alpacas');
INSERT INTO Pet VALUES ('Allin', 'Ernesta', '2001-09-30', 'F', 'focus group', 'workforce', 'Synergistic', 'Koi');
INSERT INTO Pet VALUES ('Hildagard', 'Jania', '2012-08-17', 'F', 'Implemented', 'complexity', 'Future-proofed', 'Goats');
INSERT INTO Pet VALUES ('Hilarius', 'Marissa', '2002-07-11', 'M', 'access', 'optimal', 'mobile', 'Guppy');
INSERT INTO Pet VALUES ('Holly', 'Arden', '2000-05-08', 'F', 'non-volatile', 'time-frame', 'groupware', 'Hedgehogs');
INSERT INTO Pet VALUES ('Morissa', 'Imelda', '2002-08-19', 'F', 'toolset', 'Sharable', 'zero defect', 'Goats');
INSERT INTO Pet VALUES ('Hildagard', 'Germaine', '2008-08-12', 'F', 'static', 'product', 'Total', 'Goldfish');
INSERT INTO Pet VALUES ('Hildagard', 'Pattie', '2003-05-06', 'F', 'local area network', 'extranet', 'moratorium', 'Goldfish');
INSERT INTO Pet VALUES ('Tades', 'Bantock', '2006-01-30', 'M', 'maximized', 'Exclusive', 'Profound', 'Mosquitofish');
INSERT INTO Pet VALUES ('Holly', 'Matteucci', '2002-06-05', 'F', 'real-time', 'matrix', 'projection', 'Columbines');
INSERT INTO Pet VALUES ('Belita', 'Pepper', '2001-08-16', 'M', 'tertiary', 'Optimized', 'website', 'Sheep');
INSERT INTO Pet VALUES ('Allin', 'Lisetta', '2005-10-13', 'M', 'methodology', 'systematic', 'bifurcated', 'Alpacas');
INSERT INTO Pet VALUES ('Akim', 'Charmion', '2011-12-03', 'F', 'Synchronised', 'adapter', 'Fundamental', 'Ferrets');
INSERT INTO Pet VALUES ('Winny', 'Ashlan', '2002-05-20', 'F', 'open architecture', 'Intuitive', 'portal', 'Sheep');
INSERT INTO Pet VALUES ('Morissa', 'Andy', '2000-10-11', 'F', 'hybrid', 'open architecture', 'Cross-platform', 'Cats');
INSERT INTO Pet VALUES ('Tremaine', 'Jenilee', '2012-06-27', 'F', 'system engine', 'contextually-based', 'Integrated', 'Cats');
INSERT INTO Pet VALUES ('Gianna', 'Renata', '2007-12-14', 'F', 'Mandatory', 'product', 'hub', 'Goldfish');
INSERT INTO Pet VALUES ('Romola', 'Kelley', '2001-02-06', 'M', 'archive', 'Organic', 'asynchronous', 'Mosquitofish');
INSERT INTO Pet VALUES ('Gianna', 'Ulrike', '2006-09-27', 'F', 'Programmable', 'composite', 'Object-based', 'Fowl');
INSERT INTO Pet VALUES ('Winny', 'Margrie', '2009-06-06', 'M', 'internet solution', 'matrices', 'customer loyalty', 'Alpacas');
INSERT INTO Pet VALUES ('Belita', 'Laure', '2013-10-09', 'F', 'responsive', 'foreground', 'Synergized', 'Sheep');
INSERT INTO Pet VALUES ('Romola', 'Lomath', '2001-12-26', 'M', 'hardware', 'Secured', 'Automated', 'Cattle');
INSERT INTO Pet VALUES ('Akim', 'Alys', '2014-09-09', 'M', 'Integrated', 'intermediate', 'open system', 'Columbines');
INSERT INTO Pet VALUES ('Allin', 'Brewer', '2000-05-11', 'M', 'knowledge base', 'logistical', 'moratorium', 'Goats');
INSERT INTO Pet VALUES ('Quincey', 'Judd', '2008-01-13', 'M', 'contextually-based', 'client-driven', 'actuating', 'Sheep');
INSERT INTO Pet VALUES ('Winny', 'Job', '2006-07-05', 'M', 'logistical', 'systemic', 'Multi-tiered', 'Goats');
INSERT INTO Pet VALUES ('Allin', 'Evyn', '2005-05-22', 'M', 'extranet', 'Synergized', 'methodical', 'Dogs');
INSERT INTO Pet VALUES ('Tades', 'Corie', '2000-10-19', 'M', 'model', 'radical', 'product', 'Sheep');
INSERT INTO Pet VALUES ('Tades', 'Claretta', '2001-02-14', 'F', 'Polarised', 'Re-engineered', 'Compatible', 'Guppy');
INSERT INTO Pet VALUES ('Morissa', 'Reba', '2001-12-19', 'F', 'Graphical User Interface', 'multi-state', 'Self-enabling', 'Cattle');
INSERT INTO Pet VALUES ('Allin', 'Jacquelin', '2010-10-04', 'F', 'Profound', 'monitoring', 'Fundamental', 'Cats');
INSERT INTO Pet VALUES ('Akim', 'Solomon', '2009-04-21', 'M', 'Customer-focused', 'Reverse-engineered', 'Centralized', 'Pigs');
INSERT INTO Pet VALUES ('Allin', 'Scarface', '2003-06-20', 'M', 'leverage', 'Inverse', 'fault-tolerant', 'Pigs');
INSERT INTO Pet VALUES ('Tades', 'Bobbie', '2000-05-31', 'F', 'access', '3rd generation', 'Down-sized', 'Cats');
INSERT INTO Pet VALUES ('Akim', 'Jacob', '2000-12-27', 'M', 'alliance', 'Integrated', 'stable', 'Chinchillas');
INSERT INTO Pet VALUES ('Quincey', 'Fitz', '2005-08-13', 'M', 'Visionary', 'intranet', 'framework', 'Horses');
INSERT INTO Pet VALUES ('Hilarius', 'Crystal', '2014-09-03', 'M', 'multimedia', 'hierarchy', 'Reactive', 'Koi');
INSERT INTO Pet VALUES ('Gianna', 'Flexman', '2007-08-10', 'F', 'migration', 'stable', 'knowledge base', 'Columbines');
INSERT INTO Pet VALUES ('Holly', 'Cathrine', '2009-08-31', 'F', 'non-volatile', 'moratorium', 'actuating', 'Barb');
INSERT INTO Pet VALUES ('Quincey', 'Stollwerck', '2001-09-08', 'F', 'ability', 'cohesive', 'optimal', 'Dogs');
INSERT INTO Pet VALUES ('Hilarius', 'Anastasia', '2003-10-21', 'F', 'Reactive', 'Object-based', 'forecast', 'Pigs');
INSERT INTO Pet VALUES ('Romola', 'Penny', '2013-08-05', 'M', 'multi-tasking', 'circuit', 'challenge', 'Guppy');
INSERT INTO Pet VALUES ('Akim', 'Leechman', '2000-01-12', 'M', 'Operative', 'system engine', 'Open-architected', 'Cats');
INSERT INTO Pet VALUES ('Gianna', 'Theodosia', '2009-02-18', 'M', 'installation', 'intranet', 'bifurcated', 'Cats');
INSERT INTO Pet VALUES ('Allin', 'Honatsch', '2005-01-16', 'F', 'database', 'tangible', 'Switchable', 'Horses');
INSERT INTO Pet VALUES ('Gianna', 'Cacilie', '2002-01-26', 'F', 'bottom-line', 'neutral', 'uniform', 'Cattle');
INSERT INTO Pet VALUES ('Akim', 'Liliane', '2011-08-12', 'M', 'local', 'methodology', 'mobile', 'Cattle');
INSERT INTO Pet VALUES ('Romola', 'Ashlee', '2009-09-28', 'F', 'interface', 'User-centric', 'capacity', 'Goats');
INSERT INTO Pet VALUES ('Gianna', 'Modesty', '2013-04-05', 'F', 'systemic', 'Customizable', '5th generation', 'Rodents');
INSERT INTO Pet VALUES ('Belita', 'Melisande', '2014-05-20', 'M', 'architecture', 'Reverse-engineered', 'Synchronised', 'Koi');
INSERT INTO Pet VALUES ('Tremaine', 'Stirzaker', '2011-06-23', 'F', 'emulation', 'capability', 'Monitored', 'Cattle');
INSERT INTO Pet VALUES ('Belita', 'Jodee', '2000-11-11', 'F', 'zero administration', 'mission-critical', 'productivity', 'Barb');
INSERT INTO Pet VALUES ('Tades', 'Brigitte', '2012-02-13', 'M', 'help-desk', 'budgetary management', 'foreground', 'Sheep');
INSERT INTO Pet VALUES ('Morissa', 'Adela', '2009-01-06', 'F', 'open system', 'forecast', '3rd generation', 'Cats');
INSERT INTO Pet VALUES ('Belita', 'Catina', '2013-08-20', 'F', 'initiative', 'attitude', 'multi-state', 'Columbines');
INSERT INTO Pet VALUES ('Akim', 'Aigneis', '2012-05-13', 'M', 'Expanded', 'Mandatory', 'parallelism', 'Chinchillas');
INSERT INTO Pet VALUES ('Allin', 'Ferdie', '2006-04-11', 'M', 'fault-tolerant', 'Cloned', 'adapter', 'Hedgehogs');
INSERT INTO Pet VALUES ('Quincey', 'Cherry', '2012-02-14', 'F', 'Team-oriented', 'dynamic', 'functionalities', 'Barb');
INSERT INTO Pet VALUES ('Romola', 'Karry', '2006-08-18', 'F', 'fault-tolerant', 'exuding', 'Realigned', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hildagard', 'Carlie', '2013-02-07', 'F', 'disintermediate', 'local', 'Extended', 'Ferrets');
INSERT INTO Pet VALUES ('Hilarius', 'Dorie', '2008-05-24', 'M', 'bifurcated', 'foreground', 'matrices', 'Sheep');
INSERT INTO Pet VALUES ('Hilarius', 'Estrella', '2005-11-18', 'F', 'capacity', 'algorithm', 'data-warehouse', 'Pigs');
INSERT INTO Pet VALUES ('Akim', 'Beryl', '2006-12-12', 'M', 'impactful', 'infrastructure', 'Multi-tiered', 'Koi');
INSERT INTO Pet VALUES ('Tades', 'Clo', '2014-04-02', 'F', 'system-worthy', 'flexibility', 'Mandatory', 'Sheep');
INSERT INTO Pet VALUES ('Hilarius', 'Sapshed', '2013-04-14', 'F', 'ability', 'Stand-alone', 'portal', 'Cats');
INSERT INTO Pet VALUES ('Allin', 'Hannie', '2007-10-29', 'F', 'forecast', 'Programmable', 'framework', 'Cats');
INSERT INTO Pet VALUES ('Gianna', 'Quintana', '2008-10-13', 'M', 'portal', 'local', 'frame', 'Barb');
INSERT INTO Pet VALUES ('Tades', 'Barty', '2014-05-24', 'M', 'scalable', 'Persevering', 'Progressive', 'Columbines');
INSERT INTO Pet VALUES ('Gianna', 'Rosana', '2011-11-04', 'M', 'optimal', 'methodology', 'bifurcated', 'Chinchillas');
INSERT INTO Pet VALUES ('Morissa', 'Borgesio', '2009-02-09', 'M', 'protocol', 'mobile', 'reciprocal', 'Guppy');
INSERT INTO Pet VALUES ('Gianna', 'Felicia', '2006-01-12', 'M', 'algorithm', 'attitude-oriented', 'motivating', 'Goats');
INSERT INTO Pet VALUES ('Tades', 'Liuka', '2004-05-12', 'F', 'bandwidth-monitored', 'Optional', 'Multi-lateral', 'Pigs');
INSERT INTO Pet VALUES ('Hildagard', 'Angele', '2009-01-27', 'F', 'composite', 'Diverse', 'emulation', 'Guppy');
INSERT INTO Pet VALUES ('Belita', 'Maure', '2007-11-15', 'F', 'Upgradable', 'Future-proofed', 'flexibility', 'Ferrets');
INSERT INTO Pet VALUES ('Quincey', 'Casey', '2008-08-07', 'F', 'Reduced', 'grid-enabled', 'array', 'Horses');
INSERT INTO Pet VALUES ('Hilarius', 'Rebeca', '2003-09-15', 'M', 'Synchronised', 'time-frame', 'Fully-configurable', 'Columbines');
INSERT INTO Pet VALUES ('Allin', 'Idell', '2005-10-26', 'F', 'zero defect', 'hub', 'reciprocal', 'Rodents');
INSERT INTO Pet VALUES ('Holly', 'Corinna', '2014-01-08', 'F', 'Multi-tiered', 'mobile', '3rd generation', 'Ferrets');
INSERT INTO Pet VALUES ('Holly', 'Inglebert', '2002-09-08', 'M', 'Universal', 'application', 'toolset', 'Hedgehogs');
INSERT INTO Pet VALUES ('Romola', 'Dorolice', '2007-06-30', 'F', 'orchestration', 'focus group', 'infrastructure', 'Hedgehogs');
INSERT INTO Pet VALUES ('Tades', 'Riobard', '2003-01-25', 'M', '3rd generation', 'Polarised', 'Automated', 'Cats');
INSERT INTO Pet VALUES ('Holly', 'Mallissa', '2005-04-29', 'F', 'content-based', 'Reactive', 'modular', 'Ferrets');
INSERT INTO Pet VALUES ('Tades', 'Devin', '2006-01-25', 'M', 'discrete', 'Innovative', 'Down-sized', 'Ferrets');
INSERT INTO Pet VALUES ('Gianna', 'Gracia', '2000-03-03', 'M', 'transitional', 'asynchronous', 'hierarchy', 'Guppy');
INSERT INTO Pet VALUES ('Gianna', 'Regan', '2013-12-17', 'M', 'contextually-based', 'matrix', 'orchestration', 'Columbines');
INSERT INTO Pet VALUES ('Hilarius', 'Clarine', '2008-05-09', 'F', '4th generation', 'website', 'open architecture', 'Hedgehogs');
INSERT INTO Pet VALUES ('Hildagard', 'Krissie', '2014-05-06', 'M', 'Polarised', 'open architecture', 'parallelism', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hildagard', 'Hallede', '2002-08-25', 'F', '4th generation', 'Integrated', 'implementation', 'Koi');
INSERT INTO Pet VALUES ('Tades', 'Norman', '2005-09-14', 'M', 'internet solution', 'multi-tasking', 'function', 'Cats');
INSERT INTO Pet VALUES ('Holly', 'Sheerman', '2006-11-15', 'F', 'Visionary', 'solution', 'De-engineered', 'Barb');
INSERT INTO Pet VALUES ('Quincey', 'Dulcie', '2002-10-19', 'F', 'Right-sized', 'open system', 'throughput', 'Sheep');
INSERT INTO Pet VALUES ('Belita', 'Rollin', '2002-03-26', 'F', 'implementation', 'web-enabled', 'Robust', 'Horses');
INSERT INTO Pet VALUES ('Romola', 'Cherida', '2004-08-12', 'M', 'user-facing', 'solution', 'static', 'Ferrets');
INSERT INTO Pet VALUES ('Romola', 'Minetta', '2003-08-30', 'M', 'value-added', 'local area network', 'Mandatory', 'Horses');
INSERT INTO Pet VALUES ('Winny', 'Lopez', '2011-07-25', 'M', 'Implemented', 'coherent', 'success', 'Barb');
INSERT INTO Pet VALUES ('Romola', 'Fredson', '2009-06-19', 'M', 'encompassing', 'productivity', 'Multi-layered', 'Cattle');
INSERT INTO Pet VALUES ('Winny', 'Lissi', '2013-03-24', 'M', '24 hour', 'solution-oriented', 'Decentralized', 'Fowl');
INSERT INTO Pet VALUES ('Winny', 'Krissy', '2003-10-21', 'M', 'client-driven', 'access', 'value-added', 'Barb');
INSERT INTO Pet VALUES ('Akim', 'Dennie', '2002-08-02', 'M', 'bottom-line', 'Operative', 'collaboration', 'Fowl');
INSERT INTO Pet VALUES ('Gianna', 'Nicolai', '2010-02-02', 'M', 'emulation', 'content-based', 'Persevering', 'Mosquitofish');
INSERT INTO Pet VALUES ('Quincey', 'Staci', '2001-01-18', 'M', 'monitoring', 'Sharable', 'Organic', 'Goldfish');
INSERT INTO Pet VALUES ('Belita', 'Eula', '2005-10-18', 'F', 'Graphic Interface', 'groupware', 'real-time', 'Goats');
INSERT INTO Pet VALUES ('Tades', 'Lacy', '2014-11-03', 'F', 'holistic', 'infrastructure', 'middleware', 'Rodents');
INSERT INTO Pet VALUES ('Holly', 'Lucy', '2002-12-11', 'F', 'client-driven', 'Stand-alone', 'bi-directional', 'Goldfish');
INSERT INTO Pet VALUES ('Holly', 'Goldie', '2004-08-06', 'F', 'context-sensitive', 'challenge', 'impactful', 'Hedgehogs');
INSERT INTO Pet VALUES ('Hildagard', 'Juana', '2011-08-23', 'F', 'monitoring', 'bottom-line', 'projection', 'Horses');
INSERT INTO Pet VALUES ('Hildagard', 'Bay', '2003-02-22', 'M', 'conglomeration', 'Visionary', 'system-worthy', 'Hedgehogs');
INSERT INTO Pet VALUES ('Gianna', 'Haffard', '2004-05-12', 'M', 'client-server', 'Innovative', 'instruction set', 'Goldfish');
INSERT INTO Pet VALUES ('Quincey', 'Bulgen', '2005-12-21', 'M', 'toolset', 'groupware', 'software', 'Fowl');
INSERT INTO Pet VALUES ('Akim', 'Prose', '2005-09-04', 'F', 'incremental', 'success', 'alliance', 'Fowl');
INSERT INTO Pet VALUES ('Allin', 'Klimaszewski', '2003-01-29', 'F', 'fault-tolerant', 'Synergized', 'architecture', 'Ferrets');
INSERT INTO Pet VALUES ('Morissa', 'Gabrielle', '2000-02-20', 'F', 'regional', 'zero tolerance', 'tertiary', 'Columbines');
INSERT INTO Pet VALUES ('Holly', 'Dianne', '2008-08-01', 'M', 'Proactive', 'Horizontal', 'installation', 'Goldfish');
INSERT INTO Pet VALUES ('Tremaine', 'Abagail', '2001-09-25', 'F', 'product', 'Extended', 'installation', 'Columbines');
INSERT INTO Pet VALUES ('Hildagard', 'Susette', '2010-09-16', 'F', 'emulation', 'secured line', 'Public-key', 'Goats');
INSERT INTO Pet VALUES ('Akim', 'Concettina', '2005-12-27', 'F', 'dedicated', 'utilisation', 'Self-enabling', 'Koi');
INSERT INTO Pet VALUES ('Tremaine', 'Isacsson', '2013-03-12', 'F', 'Managed', 'capacity', 'Reduced', 'Cats');
INSERT INTO Pet VALUES ('Romola', 'Dotti', '2011-10-18', 'F', 'standardization', 'systemic', 'Synergistic', 'Pigs');
INSERT INTO Pet VALUES ('Quincey', 'Cindi', '2014-07-06', 'M', 'system-worthy', 'global', 'application', 'Goats');
INSERT INTO Pet VALUES ('Tremaine', 'Alvira', '2003-09-21', 'F', 'Synergized', 'hub', 'toolset', 'Cats');
INSERT INTO Pet VALUES ('Morissa', 'Robbin', '2012-12-17', 'F', 'solution', 'circuit', 'task-force', 'Sheep');
INSERT INTO Pet VALUES ('Gianna', 'Adelaida', '2012-02-25', 'F', 'Fundamental', 'Synchronised', 'framework', 'Goldfish');
INSERT INTO Pet VALUES ('Morissa', 'Issy', '2011-08-31', 'M', 'Grass-roots', 'De-engineered', 'foreground', 'Barb');
INSERT INTO Pet VALUES ('Quincey', 'Odo', '2012-10-31', 'M', 'Configurable', 'De-engineered', 'analyzer', 'Horses');
INSERT INTO Pet VALUES ('Hilarius', 'Max', '2006-01-11', 'F', 'User-friendly', 'reciprocal', 'Persistent', 'Rabbits');
INSERT INTO Pet VALUES ('Winny', 'Sharleen', '2004-02-29', 'M', 'Configurable', 'protocol', 'Re-contextualized', 'Koi');
INSERT INTO Pet VALUES ('Romola', 'Dominga', '2014-05-07', 'F', 'static', 'foreground', 'interface', 'Horses');
INSERT INTO Pet VALUES ('Gianna', 'Cammie', '2007-11-10', 'M', 'migration', 'structure', 'application', 'Hedgehogs');
INSERT INTO Pet VALUES ('Morissa', 'Lindsay', '2012-08-21', 'M', 'Horizontal', 'Triple-buffered', 'Reactive', 'Sheep');
INSERT INTO Pet VALUES ('Hilarius', 'Colloby', '2004-04-28', 'M', 'Customer-focused', 'Digitized', 'software', 'Fowl');
INSERT INTO Pet VALUES ('Morissa', 'Morgans', '2005-02-21', 'F', 'process improvement', 'uniform', 'solution', 'Sheep');
INSERT INTO Pet VALUES ('Gianna', 'Cherianne', '2009-01-14', 'M', 'Focused', 'Extended', 'Focused', 'Goldfish');
INSERT INTO Pet VALUES ('Romola', 'Emlyn', '2011-04-06', 'F', 'encoding', 'tangible', 'multi-state', 'Rodents');
INSERT INTO Pet VALUES ('Akim', 'Claude', '2010-06-19', 'F', 'Down-sized', 'strategy', 'ability', 'Rabbits');
INSERT INTO Pet VALUES ('Tremaine', 'Arielle', '2003-04-15', 'M', 'multimedia', 'static', 'Polarised', 'Goldfish');
INSERT INTO Pet VALUES ('Hilarius', 'Aida', '2011-08-11', 'F', 'Ergonomic', 'Visionary', 'system-worthy', 'Hedgehogs');
INSERT INTO Pet VALUES ('Tremaine', 'Kesley', '2004-12-15', 'F', 'policy', 'emulation', 'Down-sized', 'Guppy');
INSERT INTO Pet VALUES ('Holly', 'Letty', '2001-09-28', 'F', 'bi-directional', 'neural-net', 'Intuitive', 'Rodents');
INSERT INTO Pet VALUES ('Romola', 'Ike', '2002-10-13', 'M', 'Synergistic', 'methodical', 'cohesive', 'Cattle');
INSERT INTO Pet VALUES ('Hildagard', 'Ozzie', '2010-05-30', 'M', 'task-force', 'Automated', 'User-friendly', 'Goats');
INSERT INTO Pet VALUES ('Belita', 'Elysha', '2001-11-19', 'M', 'Managed', 'asynchronous', 'Robust', 'Koi');
INSERT INTO Pet VALUES ('Allin', 'Jermaine', '2004-09-25', 'F', 'asymmetric', 'User-centric', 'optimal', 'Goats');
INSERT INTO Pet VALUES ('Romola', 'Codie', '2002-04-14', 'M', 'framework', 'intermediate', 'monitoring', 'Goldfish');
INSERT INTO Pet VALUES ('Tades', 'Carolann', '2005-05-19', 'F', 'Optimized', 'groupware', 'bottom-line', 'Chinchillas');
INSERT INTO Pet VALUES ('Gianna', 'Ashlen', '2004-10-09', 'F', 'cohesive', 'homogeneous', 'value-added', 'Dogs');
INSERT INTO Pet VALUES ('Holly', 'Wrennie', '2010-02-05', 'M', 'software', 'adapter', 'responsive', 'Goldfish');
INSERT INTO Pet VALUES ('Romola', 'Cleopatra', '2005-01-17', 'M', 'De-engineered', 'system engine', 'instruction set', 'Sheep');
INSERT INTO Pet VALUES ('Morissa', 'Denys', '2007-03-26', 'M', 'Assimilated', 'upward-trending', 'Graphical User Interface', 'Ferrets');
INSERT INTO Pet VALUES ('Hildagard', 'Linley', '2011-05-02', 'M', 'matrix', 'Upgradable', 'Fully-configurable', 'Cats');
INSERT INTO Pet VALUES ('Tades', 'Newall', '2002-02-08', 'F', 'paradigm', 'multi-state', 'Diverse', 'Horses');
INSERT INTO Pet VALUES ('Holly', 'Clingan', '2008-12-08', 'M', 'throughput', 'Digitized', 'Switchable', 'Columbines');
INSERT INTO Pet VALUES ('Belita', 'Butterick', '2008-08-14', 'F', 'internet solution', 'capacity', 'systemic', 'Koi');
INSERT INTO Pet VALUES ('Romola', 'Kare', '2013-03-31', 'F', 'Robust', 'multi-tasking', 'maximized', 'Ferrets');
INSERT INTO Pet VALUES ('Romola', 'Shirlee', '2004-10-27', 'F', 'Visionary', 'multimedia', 'User-centric', 'Fowl');
INSERT INTO Pet VALUES ('Morissa', 'Valencia', '2010-06-17', 'M', 'definition', 'solution-oriented', 'cohesive', 'Dogs');
INSERT INTO Pet VALUES ('Quincey', 'Randall', '2001-01-20', 'M', 'leading edge', 'content-based', 'software', 'Hedgehogs');
INSERT INTO Pet VALUES ('Tremaine', 'Stormi', '2004-01-02', 'F', 'knowledge base', 'Optional', 'encompassing', 'Ferrets');
INSERT INTO Pet VALUES ('Winny', 'Carolynn', '2009-01-18', 'M', '24/7', 'flexibility', 'tangible', 'Horses');
INSERT INTO Pet VALUES ('Winny', 'Analiese', '2009-12-20', 'F', 'didactic', 'Customer-focused', 'Re-contextualized', 'Dogs');
INSERT INTO Pet VALUES ('Winny', 'Yaknov', '2004-06-21', 'F', 'Operative', 'Future-proofed', 'holistic', 'Hedgehogs');
INSERT INTO Pet VALUES ('Belita', 'Teddy', '2007-05-10', 'F', 'analyzer', 'Operative', 'mobile', 'Goldfish');
INSERT INTO Pet VALUES ('Romola', 'Chrichton', '2012-01-23', 'F', 'Open-architected', 'help-desk', 'needs-based', 'Sheep');
INSERT INTO Pet VALUES ('Akim', 'Nedda', '2008-08-24', 'M', 'Adaptive', 'interface', 'array', 'Dogs');
INSERT INTO Pet VALUES ('Belita', 'Gus', '2006-02-18', 'M', 'directional', 'content-based', 'product', 'Hedgehogs');
INSERT INTO Pet VALUES ('Belita', 'Letizia', '2003-06-15', 'F', 'Expanded', 'Up-sized', 'Team-oriented', 'Alpacas');
INSERT INTO Pet VALUES ('Winny', 'Sapphira', '2012-02-20', 'M', 'Right-sized', 'alliance', 'Centralized', 'Koi');
INSERT INTO Pet VALUES ('Allin', 'Jamie', '2003-02-18', 'M', 'knowledge base', 'motivating', 'Compatible', 'Koi');
INSERT INTO Pet VALUES ('Morissa', 'Doug', '2007-03-14', 'M', 'intermediate', 'internet solution', 'functionalities', 'Sheep');
INSERT INTO Pet VALUES ('Hildagard', 'Pamella', '2012-02-07', 'F', 'algorithm', 'pricing structure', 'systematic', 'Alpacas');
INSERT INTO Pet VALUES ('Quincey', 'Jordan', '2011-10-28', 'F', 'Implemented', 'access', 'interface', 'Cats');
INSERT INTO Pet VALUES ('Allin', 'Francesca', '2013-12-15', 'M', 'next generation', 'Graphical User Interface', 'definition', 'Alpacas');
INSERT INTO Pet VALUES ('Quincey', 'Sisely', '2014-08-11', 'M', 'methodology', 'Team-oriented', 'needs-based', 'Koi');
INSERT INTO Pet VALUES ('Gianna', 'Nerheny', '2008-10-12', 'M', 'intermediate', 'Universal', 'Right-sized', 'Alpacas');
INSERT INTO Pet VALUES ('Holly', 'Jilleen', '2010-09-01', 'F', 'Stand-alone', 'bandwidth-monitored', 'Virtual', 'Koi');
INSERT INTO Pet VALUES ('Hildagard', 'Farand', '2009-05-30', 'M', 'asymmetric', 'optimal', 'Persevering', 'Mosquitofish');
INSERT INTO Pet VALUES ('Quincey', 'Burdas', '2011-12-31', 'M', 'web-enabled', 'interactive', 'asymmetric', 'Cattle');
INSERT INTO Pet VALUES ('Belita', 'Shanie', '2003-01-11', 'F', 'open system', 'application', 'parallelism', 'Chinchillas');
INSERT INTO Pet VALUES ('Akim', 'Chubb', '2000-04-05', 'F', 'paradigm', 'real-time', 'projection', 'Cats');
INSERT INTO Pet VALUES ('Allin', 'Shottin', '2009-11-13', 'M', 'Upgradable', 'Organized', 'encoding', 'Columbines');
INSERT INTO Pet VALUES ('Morissa', 'Moyra', '2010-07-23', 'M', 'challenge', 'system engine', 'intermediate', 'Koi');
INSERT INTO Pet VALUES ('Akim', 'Aileen', '2004-05-06', 'F', 'Open-source', 'initiative', 'Phased', 'Mosquitofish');
INSERT INTO Pet VALUES ('Holly', 'Rene', '2013-08-14', 'F', 'migration', 'Cross-group', 'strategy', 'Sheep');
INSERT INTO Pet VALUES ('Gianna', 'L;urette', '2008-10-30', 'F', 'complexity', 'Grass-roots', 'Cross-platform', 'Koi');
INSERT INTO Pet VALUES ('Winny', 'Fredi', '2014-10-11', 'F', 'zero defect', 'asymmetric', 'multi-state', 'Columbines');
INSERT INTO Pet VALUES ('Winny', 'Valerie', '2007-01-13', 'M', 'needs-based', 'Multi-channelled', 'scalable', 'Cats');
INSERT INTO Pet VALUES ('Quincey', 'Scotti', '2006-02-09', 'M', 'maximized', 'focus group', 'Secured', 'Chinchillas');
INSERT INTO Pet VALUES ('Tremaine', 'Dacy', '2004-06-26', 'M', 'Persevering', 'upward-trending', 'Innovative', 'Guppy');
INSERT INTO Pet VALUES ('Tades', 'Jacintha', '2005-09-23', 'M', 'help-desk', 'Stand-alone', 'superstructure', 'Koi');
INSERT INTO Pet VALUES ('Morissa', 'Kelila', '2004-01-30', 'M', 'leverage', 'Open-source', 'Centralized', 'Barb');
INSERT INTO Pet VALUES ('Tremaine', 'Braidon', '2003-09-21', 'M', 'Self-enabling', 'didactic', 'systematic', 'Goats');
INSERT INTO Pet VALUES ('Hilarius', 'Candra', '2009-04-05', 'F', 'Progressive', 'Visionary', 'policy', 'Columbines');
INSERT INTO Pet VALUES ('Tades', 'Aurelea', '2009-11-22', 'F', 'Diverse', 'Digitized', 'pricing structure', 'Goats');
INSERT INTO Pet VALUES ('Tades', 'Hoebart', '2006-03-17', 'M', 'Persevering', 'User-centric', 'Front-line', 'Hedgehogs');
INSERT INTO Pet VALUES ('Winny', 'Ediva', '2006-09-14', 'M', 'user-facing', 'Multi-tiered', 'User-friendly', 'Dogs');
INSERT INTO Pet VALUES ('Winny', 'Monte', '2014-12-08', 'M', 'pricing structure', 'client-server', 'bandwidth-monitored', 'Barb');
INSERT INTO Pet VALUES ('Gianna', 'Kylie', '2007-05-13', 'F', 'website', 'concept', 'upward-trending', 'Hedgehogs');
INSERT INTO Pet VALUES ('Belita', 'Fara', '2011-10-15', 'F', 'architecture', 'multi-state', 'holistic', 'Chinchillas');
INSERT INTO Pet VALUES ('Hilarius', 'Oag', '2010-08-01', 'M', 'intranet', 'adapter', 'zero tolerance', 'Rodents');
INSERT INTO Pet VALUES ('Romola', 'Kristyn', '2011-04-25', 'F', 'budgetary management', 'Cloned', 'multimedia', 'Guppy');
INSERT INTO Pet VALUES ('Morissa', 'Boken', '2008-02-27', 'M', 'groupware', 'De-engineered', 'budgetary management', 'Columbines');
INSERT INTO Pet VALUES ('Gianna', 'Kessia', '2010-04-05', 'F', 'Sharable', '5th generation', 'hub', 'Rodents');
INSERT INTO Pet VALUES ('Winny', 'Teriann', '2003-07-18', 'F', 'protocol', 'clear-thinking', 'project', 'Koi');
INSERT INTO Pet VALUES ('Morissa', 'Inessa', '2004-07-11', 'M', 'neural-net', 'Decentralized', 'Universal', 'Horses');
INSERT INTO Pet VALUES ('Belita', 'Gale', '2013-10-08', 'M', 'De-engineered', 'Profit-focused', 'Vision-oriented', 'Koi');
INSERT INTO Pet VALUES ('Belita', 'Walliw', '2007-05-04', 'M', 'Intuitive', 'portal', 'directional', 'Dogs');
INSERT INTO Pet VALUES ('Romola', 'Trescha', '2002-08-09', 'F', 'Cloned', 'middleware', 'User-friendly', 'Koi');
INSERT INTO Pet VALUES ('Morissa', 'Dehlia', '2002-05-14', 'F', 'Graphic Interface', 'De-engineered', 'neural-net', 'Cats');
INSERT INTO Pet VALUES ('Hilarius', 'Anallise', '2002-10-05', 'M', 'regional', 'encoding', 'structure', 'Fowl');
INSERT INTO Pet VALUES ('Tades', 'Nathalie', '2000-07-02', 'F', 'real-time', 'architecture', 'Multi-channelled', 'Rodents');
INSERT INTO Pet VALUES ('Tremaine', 'Amata', '2007-09-12', 'F', 'Operative', 'local', '24/7', 'Sheep');
INSERT INTO Pet VALUES ('Morissa', 'Fanchon', '2013-12-04', 'M', 'contextually-based', 'Profound', 'multi-state', 'Columbines');
INSERT INTO Pet VALUES ('Allin', 'Sophie', '2012-02-19', 'M', 'encryption', 'access', 'hierarchy', 'Guppy');
INSERT INTO Pet VALUES ('Quincey', 'Valma', '2013-04-01', 'F', 'Front-line', 'logistical', 'Multi-channelled', 'Cattle');
INSERT INTO Pet VALUES ('Belita', 'Zed', '2005-08-11', 'M', 'alliance', 'collaboration', 'full-range', 'Pigs');
INSERT INTO Pet VALUES ('Allin', 'Amory', '2000-12-19', 'M', 'modular', 'discrete', 'object-oriented', 'Goldfish');
INSERT INTO Pet VALUES ('Holly', 'Starlene', '2008-09-13', 'F', 'methodical', 'Public-key', 'monitoring', 'Pigs');
INSERT INTO Pet VALUES ('Gianna', 'Ursola', '2008-10-01', 'F', 'discrete', 'local area network', 'Team-oriented', 'Cattle');
INSERT INTO Pet VALUES ('Gianna', 'Dyana', '2013-08-08', 'M', 'attitude', 'intermediate', 'object-oriented', 'Rodents');
INSERT INTO Pet VALUES ('Quincey', 'Thelma', '2012-06-04', 'M', 'Configurable', 'tangible', 'mobile', 'Alpacas');
INSERT INTO Pet VALUES ('Tremaine', 'Natasha', '2007-09-26', 'F', 'Team-oriented', 'initiative', 'attitude', 'Guppy');
INSERT INTO Pet VALUES ('Hildagard', 'Runnicles', '2013-05-20', 'F', 'encompassing', '6th generation', 'coherent', 'Cattle');
INSERT INTO Pet VALUES ('Tades', 'Whodcoat', '2008-08-29', 'M', 'Multi-lateral', 'task-force', 'Object-based', 'Horses');
INSERT INTO Pet VALUES ('Holly', 'McCulloch', '2009-01-21', 'F', 'Inverse', '24 hour', 'holistic', 'Koi');
INSERT INTO Pet VALUES ('Belita', 'Oakman', '2007-04-11', 'F', 'architecture', 'implementation', 'installation', 'Cats');
INSERT INTO Pet VALUES ('Tades', 'Xena', '2004-05-16', 'F', 'multi-state', 'local', 'installation', 'Cattle');
INSERT INTO Pet VALUES ('Akim', 'Amelie', '2000-08-27', 'F', 'cohesive', 'Visionary', 'directional', 'Ferrets');
INSERT INTO Pet VALUES ('Allin', 'Reese', '2009-09-06', 'M', 'Synergistic', 'application', 'Enhanced', 'Chinchillas');
INSERT INTO Pet VALUES ('Romola', 'Helen-elizabeth', '2000-09-06', 'F', 'knowledge base', 'architecture', 'foreground', 'Goats');
INSERT INTO Pet VALUES ('Quincey', 'Harriette', '2014-05-07', 'F', 'framework', 'Decentralized', 'transitional', 'Mosquitofish');
INSERT INTO Pet VALUES ('Allin', 'Cirillo', '2011-02-22', 'M', 'Ergonomic', 'Pre-emptive', 'knowledge base', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hildagard', 'Shena', '2004-05-09', 'M', 'Right-sized', 'interactive', 'intermediate', 'Rabbits');
INSERT INTO Pet VALUES ('Tremaine', 'Tera', '2008-10-29', 'F', 'incremental', 'Secured', 'process improvement', 'Cattle');
INSERT INTO Pet VALUES ('Winny', 'Mollen', '2012-04-07', 'M', 'support', 'success', 'time-frame', 'Horses');
INSERT INTO Pet VALUES ('Romola', 'Ortler', '2009-06-23', 'M', 'Fundamental', 'adapter', 'fresh-thinking', 'Alpacas');
INSERT INTO Pet VALUES ('Quincey', 'Gates', '2011-03-15', 'M', 'directional', 'Integrated', 'multi-state', 'Mosquitofish');
INSERT INTO Pet VALUES ('Allin', 'Rhona', '2006-03-30', 'M', 'local', 'Graphic Interface', 'heuristic', 'Pigs');
INSERT INTO Pet VALUES ('Romola', 'Rianon', '2005-02-21', 'M', 'Business-focused', 'bifurcated', 'alliance', 'Fowl');
INSERT INTO Pet VALUES ('Holly', 'Harriett', '2006-04-21', 'F', '24 hour', 'Reactive', 'mobile', 'Hedgehogs');
INSERT INTO Pet VALUES ('Winny', 'Zaneta', '2000-10-10', 'M', 'intranet', 'conglomeration', 'Grass-roots', 'Koi');
INSERT INTO Pet VALUES ('Gianna', 'Dominique', '2000-05-06', 'F', 'logistical', 'Focused', 'moderator', 'Columbines');
INSERT INTO Pet VALUES ('Allin', 'Brier', '2011-10-20', 'F', 'Function-based', 'disintermediate', 'intangible', 'Koi');
INSERT INTO Pet VALUES ('Tades', 'Kari', '2000-07-28', 'F', 'disintermediate', 'Front-line', 'Cross-group', 'Rodents');
INSERT INTO Pet VALUES ('Holly', 'Jo-anne', '2000-11-22', 'M', 'bottom-line', 'artificial intelligence', 'Organic', 'Dogs');
INSERT INTO Pet VALUES ('Hildagard', 'Onida', '2012-11-27', 'F', 'explicit', 'scalable', 'value-added', 'Guppy');
INSERT INTO Pet VALUES ('Holly', 'Isaiah', '2009-06-09', 'M', 'intranet', 'Focused', 'mobile', 'Alpacas');
INSERT INTO Pet VALUES ('Allin', 'Celestine', '2004-07-22', 'M', 'Inverse', 'systemic', 'composite', 'Guppy');
INSERT INTO Pet VALUES ('Winny', 'Fianna', '2010-01-31', 'F', 'secondary', 'internet solution', 'Graphical User Interface', 'Rabbits');
INSERT INTO Pet VALUES ('Hilarius', 'Kalie', '2004-08-12', 'F', 'Front-line', 'Fundamental', 'Public-key', 'Columbines');
INSERT INTO Pet VALUES ('Belita', 'Deedee', '2006-04-20', 'M', 'Organic', 'adapter', 'Right-sized', 'Sheep');
INSERT INTO Pet VALUES ('Tremaine', 'Giselle', '2007-11-19', 'F', 'tertiary', 'Multi-lateral', 'impactful', 'Alpacas');
INSERT INTO Pet VALUES ('Tades', 'Farah', '2005-05-12', 'F', 'Extended', 'forecast', 'groupware', 'Goldfish');
INSERT INTO Pet VALUES ('Gianna', 'Antonelli', '2000-08-31', 'F', 'policy', 'Integrated', 'Persistent', 'Sheep');
INSERT INTO Pet VALUES ('Hildagard', 'Nissie', '2007-04-09', 'F', 'background', 'ability', 'Versatile', 'Dogs');
INSERT INTO Pet VALUES ('Allin', 'Gizela', '2004-02-29', 'M', 'productivity', 'zero defect', 'Sharable', 'Fowl');
INSERT INTO Pet VALUES ('Allin', 'Trenna', '2001-11-16', 'M', '6th generation', 'Multi-lateral', 'Virtual', 'Rabbits');
INSERT INTO Pet VALUES ('Quincey', 'Blockwell', '2014-04-17', 'F', 'Optimized', 'knowledge user', 'Diverse', 'Chinchillas');
INSERT INTO Pet VALUES ('Quincey', 'Bowie', '2011-07-13', 'M', 'Up-sized', 'Profound', 'mission-critical', 'Cattle');
INSERT INTO Pet VALUES ('Akim', 'Kizzee', '2002-09-01', 'M', 'multi-tasking', 'core', 'Automated', 'Alpacas');
INSERT INTO Pet VALUES ('Romola', 'Selina', '2000-04-30', 'F', 'matrices', 'Inverse', 'methodology', 'Pigs');
INSERT INTO Pet VALUES ('Akim', 'Bulteel', '2014-03-31', 'F', 'foreground', 'installation', 'content-based', 'Chinchillas');
INSERT INTO Pet VALUES ('Allin', 'Lambricht', '2006-05-30', 'F', 'strategy', 'product', 'analyzer', 'Pigs');
INSERT INTO Pet VALUES ('Tremaine', 'Lyndsie', '2005-04-22', 'M', 'maximized', 'product', 'encompassing', 'Rabbits');
INSERT INTO Pet VALUES ('Romola', 'Annmaria', '2001-03-29', 'M', 'Intuitive', 'policy', 'model', 'Rabbits');
INSERT INTO Pet VALUES ('Belita', 'Joane', '2002-08-04', 'M', 'protocol', 'neutral', 'dynamic', 'Guppy');
INSERT INTO Pet VALUES ('Romola', 'Brett', '2001-03-28', 'F', 'secured line', 'complexity', 'interactive', 'Rodents');
INSERT INTO Pet VALUES ('Quincey', 'Jarred', '2014-01-29', 'M', 'structure', 'array', 'monitoring', 'Chinchillas');
INSERT INTO Pet VALUES ('Winny', 'Neda', '2004-10-21', 'F', 'encompassing', 'leading edge', 'collaboration', 'Pigs');
INSERT INTO Pet VALUES ('Belita', 'Rina', '2005-09-29', 'M', 'Virtual', 'actuating', 'Robust', 'Fowl');
INSERT INTO Pet VALUES ('Hilarius', 'Trisha', '2006-08-26', 'M', 'monitoring', 'needs-based', 'reciprocal', 'Rodents');
INSERT INTO Pet VALUES ('Morissa', 'Ryan', '2003-03-15', 'M', 'Cloned', 'neutral', 'web-enabled', 'Cattle');
INSERT INTO Pet VALUES ('Quincey', 'Breanne', '2007-01-26', 'M', 'attitude', 'instruction set', 'contingency', 'Fowl');
INSERT INTO Pet VALUES ('Gianna', 'Austin', '2002-11-22', 'F', 'Multi-layered', 'protocol', 'Down-sized', 'Guppy');
INSERT INTO Pet VALUES ('Tremaine', 'Izkovicz', '2006-01-12', 'M', 'responsive', 'homogeneous', 'cohesive', 'Chinchillas');
INSERT INTO Pet VALUES ('Hildagard', 'Bernadene', '2000-09-05', 'F', 'Extended', 'context-sensitive', 'migration', 'Pigs');
INSERT INTO Pet VALUES ('Morissa', 'Jessi', '2009-08-13', 'M', 'Multi-channelled', 'Upgradable', 'Right-sized', 'Goldfish');
INSERT INTO Pet VALUES ('Romola', 'Marice', '2007-08-03', 'F', 'Focused', 'system-worthy', 'User-centric', 'Goats');
INSERT INTO Pet VALUES ('Allin', 'Magnum', '2008-01-09', 'M', 'Realigned', 'radical', 'grid-enabled', 'Alpacas');
INSERT INTO Pet VALUES ('Romola', 'Kelsey', '2006-03-12', 'M', 'capability', 'needs-based', 'support', 'Fowl');
INSERT INTO Pet VALUES ('Allin', 'Allis', '2000-01-30', 'F', 'infrastructure', 'next generation', 'interface', 'Hedgehogs');
INSERT INTO Pet VALUES ('Gianna', 'Mellisent', '2010-01-08', 'M', 'encompassing', 'throughput', 'interface', 'Guppy');
INSERT INTO Pet VALUES ('Gianna', 'Marcie', '2004-05-23', 'M', 'customer loyalty', 'user-facing', 'responsive', 'Hedgehogs');
INSERT INTO Pet VALUES ('Hilarius', 'Marousek', '2009-10-08', 'F', 'executive', 'value-added', 'Optimized', 'Sheep');
INSERT INTO Pet VALUES ('Morissa', 'Riglar', '2012-03-10', 'M', 'Phased', 'Managed', 'budgetary management', 'Mosquitofish');
INSERT INTO Pet VALUES ('Belita', 'Marna', '2003-09-14', 'F', 'paradigm', 'high-level', 'client-server', 'Rabbits');
INSERT INTO Pet VALUES ('Tremaine', 'Umeko', '2013-06-28', 'F', 'Face to face', 'national', 'composite', 'Mosquitofish');
INSERT INTO Pet VALUES ('Akim', 'Alysia', '2005-03-15', 'M', 'ability', 'artificial intelligence', 'tertiary', 'Koi');
INSERT INTO Pet VALUES ('Morissa', 'Ginger', '2010-09-29', 'M', 'Operative', 'Cross-platform', 'maximized', 'Cats');
INSERT INTO Pet VALUES ('Gianna', 'Silvana', '2001-09-24', 'M', 'Focused', '24 hour', 'Optimized', 'Guppy');
INSERT INTO Pet VALUES ('Tades', 'Freddi', '2006-08-31', 'F', 'methodical', 'dedicated', 'dynamic', 'Dogs');
INSERT INTO Pet VALUES ('Belita', 'Bobine', '2007-01-30', 'F', 'Robust', 'capacity', 'Fundamental', 'Horses');
INSERT INTO Pet VALUES ('Quincey', 'Romola', '2000-07-14', 'M', 'secondary', 'Centralized', 'homogeneous', 'Pigs');
INSERT INTO Pet VALUES ('Quincey', 'Karmen', '2001-09-17', 'M', 'Multi-layered', 'zero administration', 'Robust', 'Hedgehogs');
INSERT INTO Pet VALUES ('Tades', 'Tallou', '2013-02-21', 'F', 'empowering', 'contextually-based', 'Total', 'Fowl');
INSERT INTO Pet VALUES ('Quincey', 'Berget', '2013-01-20', 'F', 'analyzing', 'knowledge user', 'Front-line', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hilarius', 'Evey', '2014-08-31', 'F', 'national', 'web-enabled', 'superstructure', 'Koi');
INSERT INTO Pet VALUES ('Belita', 'Salomi', '2013-01-29', 'F', 'optimal', 'hub', 'User-friendly', 'Koi');
INSERT INTO Pet VALUES ('Tades', 'Fabien', '2006-09-12', 'M', 'Digitized', 'non-volatile', 'Multi-channelled', 'Chinchillas');
INSERT INTO Pet VALUES ('Hildagard', 'Evangelia', '2000-01-18', 'M', 'Streamlined', 'analyzer', 'Inverse', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hildagard', 'Junina', '2006-07-27', 'M', 'task-force', 'didactic', 'static', 'Cats');
INSERT INTO Pet VALUES ('Akim', 'Ruby', '2009-03-27', 'M', 'strategy', 'Versatile', 'secured line', 'Rodents');
INSERT INTO Pet VALUES ('Hildagard', 'Gerladina', '2005-09-24', 'F', 'non-volatile', 'context-sensitive', 'parallelism', 'Chinchillas');
INSERT INTO Pet VALUES ('Allin', 'Gertie', '2005-12-31', 'F', 'paradigm', 'database', 'next generation', 'Chinchillas');
INSERT INTO Pet VALUES ('Gianna', 'Nelie', '2000-04-04', 'M', 'matrices', 'optimal', 'Compatible', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hildagard', 'Emlen', '2010-09-03', 'F', 'next generation', 'tangible', 'multi-tasking', 'Guppy');
INSERT INTO Pet VALUES ('Tades', 'Kilfoyle', '2014-11-20', 'F', 'secondary', 'Triple-buffered', 'application', 'Cattle');
INSERT INTO Pet VALUES ('Tremaine', 'Rhodie', '2011-09-13', 'M', 'Right-sized', 'Devolved', 'neutral', 'Cats');
INSERT INTO Pet VALUES ('Tades', 'Vittorio', '2002-06-18', 'M', 'policy', 'adapter', 'client-driven', 'Mosquitofish');
INSERT INTO Pet VALUES ('Romola', 'Jeth', '2010-04-03', 'M', 'orchestration', 'complexity', 'Intuitive', 'Goats');
INSERT INTO Pet VALUES ('Romola', 'Meghan', '2006-10-26', 'F', 'policy', 'zero defect', 'Inverse', 'Pigs');
INSERT INTO Pet VALUES ('Hildagard', 'Serene', '2006-03-03', 'F', 'Expanded', 'project', 'Function-based', 'Sheep');
INSERT INTO Pet VALUES ('Hildagard', 'Collette', '2009-01-14', 'M', 'Re-engineered', 'Reactive', 'initiative', 'Rabbits');
INSERT INTO Pet VALUES ('Holly', 'Remirez', '2005-12-15', 'F', 'Fundamental', 'Phased', 'secondary', 'Alpacas');
INSERT INTO Pet VALUES ('Belita', 'Long', '2012-08-09', 'F', 'open system', 'Fundamental', 'capability', 'Ferrets');
INSERT INTO Pet VALUES ('Allin', 'Venita', '2013-03-03', 'F', 'Secured', 'mission-critical', 'Reverse-engineered', 'Goldfish');
INSERT INTO Pet VALUES ('Holly', 'Grete', '2002-03-12', 'M', 'Future-proofed', 'homogeneous', 'Organic', 'Goldfish');
INSERT INTO Pet VALUES ('Tades', 'Cherin', '2001-06-07', 'M', 'Open-source', 'asynchronous', 'frame', 'Cattle');
INSERT INTO Pet VALUES ('Morissa', 'Roseann', '2010-03-07', 'F', 'installation', 'Ergonomic', 'Advanced', 'Goldfish');
INSERT INTO Pet VALUES ('Winny', 'Suzi', '2006-01-21', 'F', 'website', 'dedicated', 'Diverse', 'Goldfish');
INSERT INTO Pet VALUES ('Winny', 'Chaffer', '2007-06-29', 'M', 'matrices', 'support', 'Object-based', 'Alpacas');
INSERT INTO Pet VALUES ('Romola', 'Goggan', '2005-12-04', 'M', 'Upgradable', 'flexibility', 'static', 'Cattle');
INSERT INTO Pet VALUES ('Hildagard', 'Jaymee', '2012-08-27', 'F', 'projection', 'projection', 'methodology', 'Goldfish');
INSERT INTO Pet VALUES ('Tremaine', 'Chantalle', '2008-03-13', 'F', 'functionalities', 'encoding', 'incremental', 'Ferrets');
INSERT INTO Pet VALUES ('Holly', 'Evy', '2002-07-25', 'M', 'secondary', 'Sharable', 'Intuitive', 'Cats');
INSERT INTO Pet VALUES ('Tades', 'Allys', '2000-09-29', 'M', 'incremental', 'Front-line', 'contingency', 'Alpacas');
INSERT INTO Pet VALUES ('Tades', 'Svend', '2011-02-07', 'M', 'Open-source', 'Seamless', 'bottom-line', 'Ferrets');
INSERT INTO Pet VALUES ('Gianna', 'Mano', '2000-04-28', 'M', 'Right-sized', 'Up-sized', 'dedicated', 'Horses');
INSERT INTO Pet VALUES ('Morissa', 'Alasteir', '2002-05-25', 'M', 'database', 'productivity', 'Programmable', 'Hedgehogs');
INSERT INTO Pet VALUES ('Quincey', 'Genny', '2013-05-30', 'F', 'success', 'standardization', 'neutral', 'Sheep');
INSERT INTO Pet VALUES ('Belita', 'Noell', '2012-04-24', 'F', 'leverage', 'actuating', 'alliance', 'Goats');
INSERT INTO Pet VALUES ('Belita', 'Iormina', '2005-10-28', 'F', 'structure', 'migration', 'Total', 'Columbines');
INSERT INTO Pet VALUES ('Morissa', 'Erin', '2012-06-09', 'M', 'workforce', 'Implemented', 'optimizing', 'Cattle');
INSERT INTO Pet VALUES ('Morissa', 'Cindra', '2010-10-31', 'F', 'middleware', 'Devolved', 'reciprocal', 'Horses');
INSERT INTO Pet VALUES ('Holly', 'Brenn', '2003-03-18', 'F', 'context-sensitive', 'intranet', 'knowledge base', 'Goldfish');
INSERT INTO Pet VALUES ('Allin', 'Clarance', '2009-02-15', 'M', 'Multi-layered', 'Digitized', 'hardware', 'Cats');
INSERT INTO Pet VALUES ('Gianna', 'Gratiana', '2009-05-20', 'M', 'attitude', 'Stand-alone', 'projection', 'Koi');
INSERT INTO Pet VALUES ('Belita', 'Melosa', '2001-09-11', 'F', 'directional', 'Down-sized', 'multi-tasking', 'Sheep');
INSERT INTO Pet VALUES ('Belita', 'Bettine', '2002-01-16', 'M', 'attitude-oriented', 'systematic', 'Total', 'Chinchillas');
INSERT INTO Pet VALUES ('Morissa', 'Vivien', '2009-03-25', 'F', 'core', 'client-driven', 'capability', 'Chinchillas');
INSERT INTO Pet VALUES ('Winny', 'Erwin', '2003-02-19', 'M', 'ability', 'upward-trending', 'responsive', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hilarius', 'Winnah', '2004-03-29', 'F', 'Progressive', 'Optional', 'impactful', 'Cats');
INSERT INTO Pet VALUES ('Romola', 'Shanda', '2007-03-31', 'F', 'architecture', 'info-mediaries', 'system engine', 'Dogs');
INSERT INTO Pet VALUES ('Hildagard', 'Joyous', '2001-01-28', 'F', 'Organic', 'extranet', 'Customizable', 'Fowl');
INSERT INTO Pet VALUES ('Tades', 'Kettie', '2003-06-25', 'F', 'Vision-oriented', 'Multi-tiered', 'interface', 'Cattle');
INSERT INTO Pet VALUES ('Tremaine', 'Jeannie', '2005-02-10', 'F', 'neutral', 'Optimized', 'tertiary', 'Guppy');
INSERT INTO Pet VALUES ('Gianna', 'Guerreau', '2014-05-02', 'M', 'Stand-alone', 'Cross-platform', 'discrete', 'Goats');
INSERT INTO Pet VALUES ('Winny', 'Amargo', '2009-03-11', 'F', 'algorithm', 'definition', 'Extended', 'Sheep');
INSERT INTO Pet VALUES ('Quincey', 'Marthena', '2014-05-10', 'F', 'solution-oriented', 'circuit', 'fresh-thinking', 'Barb');
INSERT INTO Pet VALUES ('Quincey', 'Whyffen', '2006-07-11', 'M', 'Public-key', 'matrix', 'encoding', 'Sheep');
INSERT INTO Pet VALUES ('Akim', 'Wakes', '2010-06-27', 'M', 'disintermediate', 'Universal', 'algorithm', 'Goats');
INSERT INTO Pet VALUES ('Holly', 'Natassia', '2001-06-08', 'F', 'support', 'static', '24 hour', 'Guppy');
INSERT INTO Pet VALUES ('Akim', 'Annalee', '2009-10-07', 'M', 'next generation', 'background', 'Right-sized', 'Cattle');
INSERT INTO Pet VALUES ('Allin', 'Pomfret', '2009-08-06', 'M', 'parallelism', 'extranet', 'Synergistic', 'Rodents');
INSERT INTO Pet VALUES ('Tremaine', 'Nannette', '2011-04-22', 'F', 'multi-state', 'holistic', 'Centralized', 'Cattle');
INSERT INTO Pet VALUES ('Romola', 'Lothario', '2001-08-20', 'M', 'Configurable', 'fresh-thinking', 'fault-tolerant', 'Ferrets');
INSERT INTO Pet VALUES ('Romola', 'Thia', '2002-03-18', 'F', 'project', 'Customer-focused', 'orchestration', 'Cattle');
INSERT INTO Pet VALUES ('Romola', 'Lenna', '2009-03-15', 'M', 'bandwidth-monitored', 'client-server', 'Reactive', 'Goldfish');
INSERT INTO Pet VALUES ('Romola', 'Karoline', '2007-06-16', 'F', 'migration', 'emulation', 'uniform', 'Koi');
INSERT INTO Pet VALUES ('Akim', 'Feodora', '2000-03-08', 'M', 'regional', 'matrix', 'Compatible', 'Ferrets');
INSERT INTO Pet VALUES ('Tremaine', 'Harle', '2007-10-23', 'F', 'Digitized', 'didactic', 'stable', 'Columbines');
INSERT INTO Pet VALUES ('Winny', 'Saudra', '2001-02-05', 'M', 'software', 'Profit-focused', 'frame', 'Rodents');
INSERT INTO Pet VALUES ('Hildagard', 'Odelle', '2012-06-07', 'F', 'Total', 'projection', 'Managed', 'Cattle');
INSERT INTO Pet VALUES ('Holly', 'Carlota', '2011-02-24', 'F', 'analyzing', 'Business-focused', 'Re-contextualized', 'Mosquitofish');
INSERT INTO Pet VALUES ('Morissa', 'Tessi', '2006-06-19', 'F', 'Distributed', 'Realigned', 'Vision-oriented', 'Chinchillas');
INSERT INTO Pet VALUES ('Romola', 'Halimeda', '2001-08-05', 'M', 'Optimized', 'concept', 'approach', 'Sheep');
INSERT INTO Pet VALUES ('Allin', 'Margie', '2013-05-23', 'M', 'infrastructure', 'Synergized', 'artificial intelligence', 'Fowl');
INSERT INTO Pet VALUES ('Gianna', 'Caro', '2003-09-18', 'M', 'Vision-oriented', 'bifurcated', 'discrete', 'Fowl');
INSERT INTO Pet VALUES ('Hildagard', 'Sari', '2014-11-20', 'F', 'Enterprise-wide', 'User-centric', 'local area network', 'Goldfish');
INSERT INTO Pet VALUES ('Hilarius', 'Zelma', '2003-07-31', 'F', 'flexibility', 'Mandatory', 'Multi-channelled', 'Cattle');
INSERT INTO Pet VALUES ('Tades', 'Katina', '2010-05-01', 'M', 'Multi-channelled', 'firmware', 'algorithm', 'Barb');
INSERT INTO Pet VALUES ('Gianna', 'Briana', '2001-04-22', 'M', 'Horizontal', 'full-range', 'grid-enabled', 'Dogs');
INSERT INTO Pet VALUES ('Hilarius', 'Dowding', '2004-12-03', 'M', 'optimal', 'grid-enabled', 'throughput', 'Guppy');
INSERT INTO Pet VALUES ('Quincey', 'Lorelle', '2009-08-05', 'M', 'array', 'website', 'core', 'Dogs');
INSERT INTO Pet VALUES ('Morissa', 'Reta', '2002-12-12', 'M', 'foreground', 'artificial intelligence', '24 hour', 'Mosquitofish');
INSERT INTO Pet VALUES ('Morissa', 'Seyers', '2008-08-15', 'M', 'Digitized', 'interactive', 'Re-contextualized', 'Fowl');
INSERT INTO Pet VALUES ('Gianna', 'Valery', '2009-12-14', 'F', 'open system', 'bifurcated', 'standardization', 'Rodents');
INSERT INTO Pet VALUES ('Hildagard', 'Stacy', '2005-03-20', 'M', 'bi-directional', 'upward-trending', 'Phased', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hildagard', 'Ebony', '2001-06-12', 'M', 'Multi-lateral', 'leading edge', 'time-frame', 'Guppy');
INSERT INTO Pet VALUES ('Hildagard', 'Coralie', '2003-08-08', 'M', 'didactic', '24/7', 'leverage', 'Pigs');
INSERT INTO Pet VALUES ('Belita', 'Lynda', '2007-05-16', 'F', 'empowering', 'productivity', 'needs-based', 'Horses');
INSERT INTO Pet VALUES ('Hildagard', 'Debera', '2012-07-08', 'F', 'Automated', 'knowledge base', 'Exclusive', 'Guppy');
INSERT INTO Pet VALUES ('Hilarius', 'Gertrudis', '2013-05-19', 'M', 'Streamlined', 'Function-based', 'actuating', 'Rabbits');
INSERT INTO Pet VALUES ('Quincey', 'Saba', '2010-02-06', 'F', 'Team-oriented', 'Inverse', 'Down-sized', 'Horses');
INSERT INTO Pet VALUES ('Belita', 'Merralee', '2006-01-29', 'F', 'Mandatory', 'website', 'Open-architected', 'Mosquitofish');
INSERT INTO Pet VALUES ('Allin', 'Estelle', '2013-04-10', 'M', 'zero defect', 'middleware', 'mobile', 'Dogs');
INSERT INTO Pet VALUES ('Holly', 'Ruthie', '2002-11-25', 'M', '3rd generation', 'Persevering', 'context-sensitive', 'Cattle');
INSERT INTO Pet VALUES ('Hilarius', 'Dick', '2002-06-03', 'M', 'Face to face', 'Profit-focused', 'workforce', 'Koi');
INSERT INTO Pet VALUES ('Winny', 'Peder', '2006-09-26', 'M', 'model', 'benchmark', 'interface', 'Rodents');
INSERT INTO Pet VALUES ('Hildagard', 'Irita', '2011-07-14', 'M', 'analyzing', 'responsive', 'Reactive', 'Cattle');
INSERT INTO Pet VALUES ('Tades', 'Kirbee', '2010-01-17', 'M', 'Enhanced', 'Innovative', 'Seamless', 'Goats');
INSERT INTO Pet VALUES ('Winny', 'Adena', '2009-11-21', 'M', 'workforce', 'Enhanced', 'intangible', 'Rabbits');
INSERT INTO Pet VALUES ('Winny', 'Alika', '2012-06-19', 'F', 'eco-centric', 'methodical', 'Synchronised', 'Sheep');
INSERT INTO Pet VALUES ('Tades', 'Somerset', '2001-04-20', 'M', 'uniform', 'Fully-configurable', 'multi-tasking', 'Dogs');
INSERT INTO Pet VALUES ('Hildagard', 'Schlagtmans', '2011-11-03', 'M', 'project', 'bandwidth-monitored', 'Progressive', 'Sheep');
INSERT INTO Pet VALUES ('Tremaine', 'Evania', '2012-08-07', 'M', 'data-warehouse', 'array', 'database', 'Dogs');
INSERT INTO Pet VALUES ('Gianna', 'Frannie', '2012-01-01', 'F', 'Visionary', 'Streamlined', 'Persevering', 'Ferrets');
INSERT INTO Pet VALUES ('Belita', 'Dita', '2007-12-31', 'F', 'workforce', '24 hour', 'superstructure', 'Goldfish');
INSERT INTO Pet VALUES ('Tades', 'Eversley', '2004-05-21', 'M', 'Public-key', 'ability', 'tangible', 'Sheep');
INSERT INTO Pet VALUES ('Tremaine', 'Larisa', '2003-05-17', 'F', 'Customizable', 'artificial intelligence', 'responsive', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hildagard', 'Cristionna', '2003-05-06', 'F', 'portal', 'application', 'full-range', 'Goats');
INSERT INTO Pet VALUES ('Winny', 'Cristina', '2011-05-27', 'M', 'groupware', 'utilisation', 'database', 'Mosquitofish');
INSERT INTO Pet VALUES ('Holly', 'McKernan', '2007-09-05', 'F', 'bifurcated', 'client-driven', 'approach', 'Sheep');
INSERT INTO Pet VALUES ('Holly', 'Brigida', '2008-09-01', 'F', 'modular', 'multi-tasking', 'local area network', 'Alpacas');
INSERT INTO Pet VALUES ('Quincey', 'Cloe', '2000-10-02', 'M', 'coherent', 'Mandatory', 'approach', 'Hedgehogs');
INSERT INTO Pet VALUES ('Belita', 'Keenlyside', '2014-07-23', 'F', 'neutral', 'static', 'stable', 'Rabbits');
INSERT INTO Pet VALUES ('Hildagard', 'Mord', '2012-07-28', 'M', '3rd generation', 'Customizable', 'Triple-buffered', 'Cattle');
INSERT INTO Pet VALUES ('Holly', 'Alfi', '2011-11-18', 'F', 'Public-key', '4th generation', 'User-friendly', 'Chinchillas');
INSERT INTO Pet VALUES ('Quincey', 'Franny', '2013-12-01', 'M', 'Compatible', 'matrices', 'Open-architected', 'Fowl');
INSERT INTO Pet VALUES ('Hildagard', 'Maddy', '2013-12-25', 'M', 'intermediate', 'website', 'Customer-focused', 'Alpacas');
INSERT INTO Pet VALUES ('Allin', 'Mickie', '2011-08-16', 'M', 'framework', 'zero defect', 'framework', 'Horses');
INSERT INTO Pet VALUES ('Winny', 'Atyeo', '2009-05-22', 'F', 'Ameliorated', 'model', 'time-frame', 'Ferrets');
INSERT INTO Pet VALUES ('Winny', 'Gina', '2003-07-04', 'F', 'Configurable', 'heuristic', 'maximized', 'Barb');
INSERT INTO Pet VALUES ('Romola', 'Lever', '2004-10-20', 'M', 'bandwidth-monitored', 'Optimized', 'function', 'Horses');
INSERT INTO Pet VALUES ('Hilarius', 'Jorrie', '2014-10-26', 'F', 'workforce', 'alliance', 'groupware', 'Chinchillas');
INSERT INTO Pet VALUES ('Hilarius', 'Cara', '2004-09-16', 'F', 'Multi-channelled', 'Networked', 'Horizontal', 'Dogs');
INSERT INTO Pet VALUES ('Gianna', 'Nolana', '2013-05-05', 'F', 'interface', 'analyzer', 'support', 'Mosquitofish');
INSERT INTO Pet VALUES ('Akim', 'Min', '2000-05-26', 'F', 'Advanced', 'impactful', 'tangible', 'Horses');
INSERT INTO Pet VALUES ('Gianna', 'Rennie', '2008-03-14', 'F', 'Automated', 'web-enabled', 'system-worthy', 'Mosquitofish');
INSERT INTO Pet VALUES ('Quincey', 'Eustacia', '2010-11-05', 'F', 'Exclusive', 'intranet', 'bi-directional', 'Columbines');
INSERT INTO Pet VALUES ('Quincey', 'Darya', '2006-02-17', 'F', 'emulation', 'Open-source', 'Cloned', 'Fowl');
INSERT INTO Pet VALUES ('Hildagard', 'Briano', '2004-02-25', 'M', 'conglomeration', 'Implemented', 'Seamless', 'Fowl');
INSERT INTO Pet VALUES ('Morissa', 'Isahella', '2014-07-10', 'F', 'Exclusive', 'access', 'clear-thinking', 'Fowl');
INSERT INTO Pet VALUES ('Quincey', 'Marlo', '2007-07-23', 'F', 'Inverse', 'responsive', 'Exclusive', 'Fowl');
INSERT INTO Pet VALUES ('Gianna', 'Whitney', '2001-04-07', 'F', 'complexity', 'composite', 'encoding', 'Cats');
INSERT INTO Pet VALUES ('Hildagard', 'Hesther', '2008-12-10', 'M', 'eco-centric', 'Ameliorated', 'task-force', 'Columbines');
INSERT INTO Pet VALUES ('Quincey', 'Sumner', '2009-03-15', 'M', 'De-engineered', 'open system', 'asynchronous', 'Goldfish');
INSERT INTO Pet VALUES ('Belita', 'Jayne', '2001-05-08', 'M', 'Future-proofed', 'dedicated', 'foreground', 'Hedgehogs');
INSERT INTO Pet VALUES ('Tades', 'Tildy', '2008-03-14', 'F', 'even-keeled', 'coherent', 'ability', 'Pigs');
INSERT INTO Pet VALUES ('Gianna', 'Kelci', '2000-06-25', 'M', 'motivating', 'open system', 'Decentralized', 'Fowl');
INSERT INTO Pet VALUES ('Morissa', 'Helenelizabeth', '2002-01-16', 'M', 'User-centric', 'asynchronous', 'software', 'Ferrets');
INSERT INTO Pet VALUES ('Tremaine', 'Libbi', '2007-01-29', 'F', 'capability', 'analyzer', 'Implemented', 'Cats');
INSERT INTO Pet VALUES ('Hildagard', 'Gavra', '2013-04-21', 'M', 'composite', 'object-oriented', 'groupware', 'Cats');
INSERT INTO Pet VALUES ('Tremaine', 'Emmalee', '2005-04-03', 'F', 'Universal', 'incremental', 'Quality-focused', 'Cats');
INSERT INTO Pet VALUES ('Gianna', 'Le Galle', '2013-06-02', 'F', 'framework', 'well-modulated', 'heuristic', 'Ferrets');
INSERT INTO Pet VALUES ('Quincey', 'Goscar', '2009-09-09', 'M', 'projection', 'help-desk', 'systematic', 'Pigs');
INSERT INTO Pet VALUES ('Akim', 'Reubbens', '2005-07-10', 'F', 'system engine', 'Self-enabling', 'full-range', 'Ferrets');
INSERT INTO Pet VALUES ('Holly', 'Ekaterina', '2009-03-13', 'F', 'encompassing', 'leverage', 'project', 'Chinchillas');
INSERT INTO Pet VALUES ('Allin', 'Lambis', '2012-03-01', 'M', 'Optional', 'secured line', 'hardware', 'Goats');
INSERT INTO Pet VALUES ('Tades', 'Basile', '2007-04-05', 'M', 'website', 'transitional', 'synergy', 'Sheep');
INSERT INTO Pet VALUES ('Hilarius', 'Worth', '2010-07-25', 'M', 'multi-tasking', 'Realigned', 'success', 'Dogs');
INSERT INTO Pet VALUES ('Hilarius', 'Charmain', '2009-09-10', 'F', 'task-force', 'service-desk', 'leverage', 'Guppy');
INSERT INTO Pet VALUES ('Winny', 'Noelyn', '2011-04-29', 'F', 'disintermediate', 'multi-tasking', 'paradigm', 'Guppy');
INSERT INTO Pet VALUES ('Akim', 'Gipsy', '2012-10-04', 'M', 'coherent', 'Distributed', 'multi-state', 'Mosquitofish');
INSERT INTO Pet VALUES ('Holly', 'Chelsey', '2014-12-19', 'F', 'leverage', '6th generation', 'Reactive', 'Koi');
INSERT INTO Pet VALUES ('Romola', 'Lorraine', '2002-07-12', 'M', 'Quality-focused', 'Programmable', 'Synchronised', 'Rodents');
INSERT INTO Pet VALUES ('Holly', 'Sherri', '2004-12-09', 'F', 'Secured', 'Centralized', 'Integrated', 'Pigs');
INSERT INTO Pet VALUES ('Winny', 'Clifford', '2012-12-19', 'M', 'encryption', 'service-desk', 'Centralized', 'Koi');
INSERT INTO Pet VALUES ('Gianna', 'Lian', '2013-12-08', 'M', 'Seamless', 'Self-enabling', 'model', 'Sheep');
INSERT INTO Pet VALUES ('Hilarius', 'Norina', '2007-04-25', 'F', 'Synergistic', '6th generation', 'encompassing', 'Hedgehogs');
INSERT INTO Pet VALUES ('Romola', 'Lorelei', '2009-09-22', 'M', 'Operative', 'process improvement', 'User-centric', 'Chinchillas');
INSERT INTO Pet VALUES ('Holly', 'Philomena', '2006-04-30', 'F', 'complexity', 'alliance', 'installation', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hilarius', 'Banky', '2006-06-12', 'M', 'workforce', 'standardization', 'Intuitive', 'Hedgehogs');
INSERT INTO Pet VALUES ('Tades', 'Michelina', '2011-11-17', 'F', 'attitude-oriented', 'Persistent', 'Vision-oriented', 'Fowl');
INSERT INTO Pet VALUES ('Tremaine', 'Slate', '2004-11-12', 'F', 'Balanced', 'demand-driven', 'analyzer', 'Cattle');
INSERT INTO Pet VALUES ('Gianna', 'Tally', '2014-01-31', 'F', 'even-keeled', 'structure', 'leading edge', 'Goldfish');
INSERT INTO Pet VALUES ('Holly', 'Judas', '2004-01-25', 'M', 'zero tolerance', 'Ameliorated', 'responsive', 'Horses');
INSERT INTO Pet VALUES ('Holly', 'Roze', '2012-10-27', 'M', 'emulation', 'well-modulated', 'modular', 'Rabbits');
INSERT INTO Pet VALUES ('Quincey', 'Terri', '2009-09-23', 'M', 'Front-line', 'workforce', 'Progressive', 'Goldfish');
INSERT INTO Pet VALUES ('Holly', 'Emelyne', '2002-01-31', 'M', 'Re-contextualized', 'Re-contextualized', 'Realigned', 'Guppy');
INSERT INTO Pet VALUES ('Tades', 'Hayley', '2001-08-24', 'M', 'even-keeled', '24 hour', 'Sharable', 'Chinchillas');
INSERT INTO Pet VALUES ('Quincey', 'Renate', '2009-05-18', 'F', 'Configurable', 'intangible', 'frame', 'Goats');
INSERT INTO Pet VALUES ('Gianna', 'Courtenay', '2005-10-06', 'F', 'Configurable', 'function', 'Cross-platform', 'Fowl');
INSERT INTO Pet VALUES ('Hildagard', 'Danell', '2005-01-15', 'M', 'multi-state', 'projection', 'neutral', 'Guppy');
INSERT INTO Pet VALUES ('Romola', 'Avivah', '2014-09-26', 'F', 'projection', 'multi-state', 'protocol', 'Sheep');
INSERT INTO Pet VALUES ('Belita', 'Perla', '2003-02-14', 'M', 'attitude', 'Digitized', 'Managed', 'Dogs');
INSERT INTO Pet VALUES ('Winny', 'Oralee', '2008-11-11', 'F', 'process improvement', 'dynamic', 'value-added', 'Chinchillas');
INSERT INTO Pet VALUES ('Akim', 'Gwenneth', '2006-04-06', 'M', 'fresh-thinking', 'Virtual', 'product', 'Hedgehogs');
INSERT INTO Pet VALUES ('Hilarius', 'Jowle', '2012-06-05', 'M', 'Pre-emptive', 'Diverse', 'intranet', 'Guppy');
INSERT INTO Pet VALUES ('Holly', 'Jobey', '2007-08-04', 'F', 'Upgradable', 'scalable', 'algorithm', 'Ferrets');
INSERT INTO Pet VALUES ('Morissa', 'Strass', '2004-06-05', 'M', 'service-desk', 'array', 'solution', 'Barb');
INSERT INTO Pet VALUES ('Tremaine', 'Catlaina', '2012-01-04', 'F', 'Optional', 'asynchronous', 'internet solution', 'Rabbits');
INSERT INTO Pet VALUES ('Morissa', 'Grethel', '2014-04-12', 'M', 'internet solution', 'discrete', 'open architecture', 'Sheep');
INSERT INTO Pet VALUES ('Tremaine', 'Auguste', '2005-08-25', 'M', 'Public-key', 'Synergistic', 'product', 'Mosquitofish');
INSERT INTO Pet VALUES ('Quincey', 'Tiffie', '2012-04-10', 'F', 'analyzing', 'moratorium', 'core', 'Cattle');
INSERT INTO Pet VALUES ('Winny', 'Dorena', '2014-06-14', 'F', 'methodology', 'client-driven', 'framework', 'Cattle');
INSERT INTO Pet VALUES ('Hilarius', 'Gwenni', '2007-02-05', 'F', 'Grass-roots', 'responsive', 'exuding', 'Fowl');
INSERT INTO Pet VALUES ('Gianna', 'Pauli', '2003-11-13', 'M', 'interface', 'Face to face', 'product', 'Pigs');
INSERT INTO Pet VALUES ('Morissa', 'Hetti', '2006-01-12', 'M', 'Profit-focused', 'portal', 'Reverse-engineered', 'Cattle');
INSERT INTO Pet VALUES ('Hildagard', 'Bette', '2012-01-29', 'M', 'success', 'Distributed', 'solution-oriented', 'Columbines');
INSERT INTO Pet VALUES ('Winny', 'Rebeka', '2002-06-19', 'M', 'Fully-configurable', 'conglomeration', 'open system', 'Fowl');
INSERT INTO Pet VALUES ('Tades', 'Star', '2012-12-06', 'M', 'Compatible', 'contingency', 'moderator', 'Horses');
INSERT INTO Pet VALUES ('Morissa', 'Sissie', '2007-03-03', 'M', 'contextually-based', 'exuding', 'Synchronised', 'Cats');
INSERT INTO Pet VALUES ('Allin', 'Nertie', '2001-06-02', 'F', 'non-volatile', 'Realigned', 'Cloned', 'Goldfish');
INSERT INTO Pet VALUES ('Tremaine', 'Bernette', '2009-02-05', 'M', 'Self-enabling', 'Phased', 'Graphical User Interface', 'Barb');
INSERT INTO Pet VALUES ('Hildagard', 'Ennion', '2003-05-31', 'F', 'Stand-alone', 'middleware', 'neural-net', 'Cats');
INSERT INTO Pet VALUES ('Morissa', 'Melli', '2004-10-05', 'F', 'client-driven', 'multi-state', 'Decentralized', 'Alpacas');
INSERT INTO Pet VALUES ('Tades', 'Lillis', '2000-05-08', 'F', 'zero tolerance', 'instruction set', 'info-mediaries', 'Fowl');
INSERT INTO Pet VALUES ('Tades', 'Pugh', '2002-08-31', 'M', 'Ameliorated', 'Networked', 'Object-based', 'Horses');
INSERT INTO Pet VALUES ('Gianna', 'Ellyn', '2011-03-09', 'F', 'disintermediate', 'open architecture', 'secondary', 'Goldfish');
INSERT INTO Pet VALUES ('Quincey', 'Mei', '2008-06-13', 'F', 'impactful', 'moderator', 'client-server', 'Mosquitofish');
INSERT INTO Pet VALUES ('Holly', 'Dunstan', '2014-10-12', 'M', 'artificial intelligence', 'national', 'toolset', 'Columbines');
INSERT INTO Pet VALUES ('Belita', 'MacVean', '2000-11-13', 'M', 'intranet', 'forecast', 'challenge', 'Goldfish');
INSERT INTO Pet VALUES ('Quincey', 'Florenza', '2006-11-16', 'M', 'Devolved', 'contextually-based', 'Synergized', 'Ferrets');
INSERT INTO Pet VALUES ('Winny', 'Chicotti', '2014-09-09', 'F', 'Optimized', 'model', 'hardware', 'Rabbits');
INSERT INTO Pet VALUES ('Romola', 'Awdry', '2011-01-30', 'M', 'Multi-lateral', 'Open-architected', 'Networked', 'Barb');
INSERT INTO Pet VALUES ('Belita', 'Melicent', '2012-02-23', 'F', 'Programmable', 'application', 'artificial intelligence', 'Rodents');
INSERT INTO Pet VALUES ('Gianna', 'Vanessa', '2002-04-10', 'F', 'disintermediate', 'Persevering', 'even-keeled', 'Koi');
INSERT INTO Pet VALUES ('Hildagard', 'Micky', '2007-04-28', 'F', 'hybrid', 'well-modulated', 'object-oriented', 'Pigs');
INSERT INTO Pet VALUES ('Gianna', 'Andra', '2003-01-02', 'F', 'Cloned', 'open system', 'Distributed', 'Pigs');
INSERT INTO Pet VALUES ('Hilarius', 'Maryanne', '2013-06-14', 'M', 'Devolved', 'Versatile', 'regional', 'Rodents');
INSERT INTO Pet VALUES ('Gianna', 'Sib', '2010-10-13', 'F', 'model', 'Front-line', 'Enhanced', 'Sheep');
INSERT INTO Pet VALUES ('Hilarius', 'Wendie', '2010-08-27', 'M', 'Horizontal', 'help-desk', 'budgetary management', 'Barb');
INSERT INTO Pet VALUES ('Tremaine', 'Aline', '2004-07-25', 'F', 'frame', 'systemic', 'Horizontal', 'Fowl');
INSERT INTO Pet VALUES ('Morissa', 'Lilas', '2003-10-26', 'F', 'Balanced', 'fault-tolerant', 'Graphical User Interface', 'Fowl');
INSERT INTO Pet VALUES ('Gianna', 'Srawley', '2011-11-24', 'F', 'Streamlined', 'throughput', 'Pre-emptive', 'Koi');
INSERT INTO Pet VALUES ('Tremaine', 'Charmaine', '2013-07-18', 'M', 'interactive', 'frame', 'adapter', 'Hedgehogs');
INSERT INTO Pet VALUES ('Quincey', 'Stellino', '2013-02-18', 'M', 'value-added', 'alliance', '6th generation', 'Dogs');
INSERT INTO Pet VALUES ('Gianna', 'Glori', '2000-07-11', 'M', 'reciprocal', 'holistic', 'motivating', 'Horses');
INSERT INTO Pet VALUES ('Quincey', 'Paulina', '2000-02-27', 'M', 'Mandatory', 'Versatile', 'benchmark', 'Dogs');
INSERT INTO Pet VALUES ('Akim', 'Grimoldby', '2001-11-23', 'F', 'customer loyalty', 'dynamic', 'encompassing', 'Hedgehogs');
INSERT INTO Pet VALUES ('Hilarius', 'Jenine', '2013-04-09', 'M', 'Enhanced', 'Reduced', 'non-volatile', 'Ferrets');
INSERT INTO Pet VALUES ('Morissa', 'Lucille', '2002-06-08', 'M', 'cohesive', 'global', 'Configurable', 'Ferrets');
INSERT INTO Pet VALUES ('Allin', 'Basek', '2008-09-16', 'M', 'projection', 'toolset', 'reciprocal', 'Barb');
INSERT INTO Pet VALUES ('Morissa', 'Morena', '2008-06-27', 'M', 'optimal', 'data-warehouse', 'Devolved', 'Dogs');
INSERT INTO Pet VALUES ('Akim', 'Dolly', '2010-12-05', 'M', 'Secured', 'website', 'internet solution', 'Alpacas');
INSERT INTO Pet VALUES ('Romola', 'Megen', '2001-12-13', 'M', 'Proactive', 'pricing structure', 'system engine', 'Goldfish');
INSERT INTO Pet VALUES ('Belita', 'Sharon', '2014-07-26', 'F', 'internet solution', 'Focused', 'Object-based', 'Hedgehogs');
INSERT INTO Pet VALUES ('Hilarius', 'Lissie', '2004-02-05', 'M', 'Re-engineered', 'Phased', 'Future-proofed', 'Mosquitofish');
INSERT INTO Pet VALUES ('Romola', 'Eunice', '2008-11-10', 'M', 'Graphical User Interface', 'hardware', 'challenge', 'Cattle');
INSERT INTO Pet VALUES ('Winny', 'Ashley', '2010-09-16', 'F', 'User-friendly', 'logistical', 'Stand-alone', 'Alpacas');
INSERT INTO Pet VALUES ('Tremaine', 'Cantero', '2012-08-20', 'M', 'support', 'website', 'Devolved', 'Dogs');
INSERT INTO Pet VALUES ('Romola', 'Jaynell', '2006-05-04', 'F', 'Exclusive', 'incremental', 'parallelism', 'Goldfish');
INSERT INTO Pet VALUES ('Hildagard', 'Jesselyn', '2010-02-23', 'F', 'Customer-focused', 'throughput', 'standardization', 'Horses');
INSERT INTO Pet VALUES ('Hilarius', 'Biggerstaff', '2008-06-11', 'M', 'Automated', 'task-force', 'full-range', 'Hedgehogs');
INSERT INTO Pet VALUES ('Gianna', 'Paige', '2006-06-14', 'F', 'upward-trending', 'regional', 'workforce', 'Rabbits');
INSERT INTO Pet VALUES ('Tades', 'Domeniga', '2002-09-24', 'F', 'hardware', 'reciprocal', 'monitoring', 'Horses');
INSERT INTO Pet VALUES ('Morissa', 'Mulhall', '2009-11-23', 'M', 'contextually-based', 'Digitized', 'reciprocal', 'Rabbits');
INSERT INTO Pet VALUES ('Winny', 'Lurlene', '2005-02-11', 'M', 'Public-key', 'Streamlined', 'Reduced', 'Rodents');
INSERT INTO Pet VALUES ('Belita', 'Etheline', '2000-07-18', 'M', 'systemic', 'Reactive', 'Function-based', 'Guppy');
INSERT INTO Pet VALUES ('Hildagard', 'Faye', '2002-02-18', 'F', 'application', 'Profound', 'attitude-oriented', 'Columbines');
INSERT INTO Pet VALUES ('Tades', 'Chrysa', '2004-11-27', 'M', 'workforce', 'Mandatory', 'archive', 'Chinchillas');
INSERT INTO Pet VALUES ('Akim', 'Cecelia', '2014-03-24', 'F', 'structure', 'zero defect', 'Profound', 'Koi');
INSERT INTO Pet VALUES ('Quincey', 'Lotty', '2003-01-28', 'M', 'motivating', 'intranet', 'Automated', 'Mosquitofish');
INSERT INTO Pet VALUES ('Quincey', 'Lizette', '2001-06-26', 'M', 'paradigm', 'Object-based', 'Enterprise-wide', 'Cats');
INSERT INTO Pet VALUES ('Hilarius', 'Teresita', '2010-11-20', 'F', 'Persevering', 'artificial intelligence', 'Triple-buffered', 'Ferrets');
INSERT INTO Pet VALUES ('Hildagard', 'Lorena', '2003-03-31', 'F', 'Multi-channelled', 'Re-contextualized', 'client-server', 'Dogs');
INSERT INTO Pet VALUES ('Hildagard', 'Ariadne', '2001-10-03', 'F', 'systemic', 'frame', 'Digitized', 'Cats');
INSERT INTO Pet VALUES ('Morissa', 'Lara', '2009-08-02', 'F', 'software', 'Business-focused', 'initiative', 'Cats');
INSERT INTO Pet VALUES ('Allin', 'Lilia', '2003-06-13', 'F', 'synergy', 'Re-contextualized', 'optimizing', 'Rabbits');
INSERT INTO Pet VALUES ('Quincey', 'Ellen', '2013-09-13', 'M', 'radical', 'Organized', 'interface', 'Pigs');
INSERT INTO Pet VALUES ('Hildagard', 'Punshon', '2012-12-29', 'M', 'holistic', 'strategy', '24/7', 'Guppy');
INSERT INTO Pet VALUES ('Tades', 'Di Nisco', '2011-05-18', 'F', 'Re-engineered', 'demand-driven', 'Reverse-engineered', 'Cattle');
INSERT INTO Pet VALUES ('Gianna', 'Gretta', '2003-04-25', 'F', 'interface', 'complexity', 'strategy', 'Guppy');
INSERT INTO Pet VALUES ('Hildagard', 'Naomi', '2009-02-12', 'F', 'dynamic', 'conglomeration', 'software', 'Columbines');
INSERT INTO Pet VALUES ('Holly', 'Evill', '2001-08-31', 'F', 'Synergistic', 'Expanded', 'zero administration', 'Cats');
INSERT INTO Pet VALUES ('Holly', 'Jasmina', '2011-05-29', 'F', 'Adaptive', 'leading edge', 'frame', 'Alpacas');
INSERT INTO Pet VALUES ('Hildagard', 'Dagmar', '2013-01-14', 'M', 'implementation', 'middleware', 'uniform', 'Goldfish');
INSERT INTO Pet VALUES ('Quincey', 'Maura', '2010-09-18', 'F', 'Digitized', 'standardization', 'project', 'Rabbits');
INSERT INTO Pet VALUES ('Hildagard', 'Clemmy', '2002-06-16', 'M', 'Graphic Interface', 'Extended', 'Multi-lateral', 'Columbines');
INSERT INTO Pet VALUES ('Winny', 'Hyacinthie', '2007-12-30', 'F', 'Synchronised', 'client-server', 'synergy', 'Chinchillas');
INSERT INTO Pet VALUES ('Allin', 'Lilith', '2013-01-19', 'F', 'coherent', 'Multi-channelled', 'transitional', 'Hedgehogs');
INSERT INTO Pet VALUES ('Belita', 'Robbert', '2002-12-25', 'M', 'interactive', 'non-volatile', 'structure', 'Cats');
INSERT INTO Pet VALUES ('Hildagard', 'Carline', '2011-02-25', 'F', 'actuating', 'Organized', 'eco-centric', 'Goldfish');
INSERT INTO Pet VALUES ('Holly', 'Marguerite', '2013-01-21', 'F', 'Innovative', 'Fully-configurable', 'regional', 'Rodents');
INSERT INTO Pet VALUES ('Winny', 'Stopher', '2006-05-25', 'M', 'analyzer', 'utilisation', 'parallelism', 'Cattle');
INSERT INTO Pet VALUES ('Romola', 'Puleston', '2005-02-02', 'F', 'multi-tasking', 'cohesive', 'Fundamental', 'Hedgehogs');
INSERT INTO Pet VALUES ('Allin', 'Cyndi', '2005-06-07', 'M', '24 hour', 'intermediate', 'contextually-based', 'Goats');
INSERT INTO Pet VALUES ('Belita', 'Marie-ann', '2007-12-02', 'F', 'intangible', 'Cross-group', 'client-driven', 'Cattle');
INSERT INTO Pet VALUES ('Holly', 'Roana', '2014-06-24', 'M', 'Re-contextualized', 'Optional', 'Monitored', 'Barb');
INSERT INTO Pet VALUES ('Quincey', 'Rania', '2000-02-17', 'F', 'Cloned', 'toolset', 'empowering', 'Goats');
INSERT INTO Pet VALUES ('Holly', 'Charmane', '2009-08-30', 'F', 'Right-sized', 'pricing structure', 'systematic', 'Mosquitofish');
INSERT INTO Pet VALUES ('Quincey', 'Elicia', '2001-06-23', 'M', 'Integrated', 'solution-oriented', 'neutral', 'Koi');
INSERT INTO Pet VALUES ('Gianna', 'Peatheyjohns', '2012-04-11', 'F', 'heuristic', 'website', 'paradigm', 'Rodents');
INSERT INTO Pet VALUES ('Quincey', 'Geratt', '2012-03-19', 'M', 'Automated', 'benchmark', 'regional', 'Rodents');
INSERT INTO Pet VALUES ('Tremaine', 'Athena', '2008-11-17', 'M', 'Horizontal', 'Reduced', 'Secured', 'Rodents');
INSERT INTO Pet VALUES ('Tremaine', 'Tildie', '2004-09-29', 'M', 'Focused', 'algorithm', 'time-frame', 'Barb');
INSERT INTO Pet VALUES ('Akim', 'Di Maria', '2005-08-20', 'M', 'Networked', 'zero tolerance', 'Fully-configurable', 'Horses');
INSERT INTO Pet VALUES ('Allin', 'Allderidge', '2003-07-27', 'F', 'Proactive', 'archive', 'encryption', 'Rodents');
INSERT INTO Pet VALUES ('Winny', 'Delora', '2002-10-30', 'F', 'Team-oriented', 'application', 'encryption', 'Ferrets');
INSERT INTO Pet VALUES ('Quincey', 'Myranda', '2005-06-30', 'M', 'Adaptive', 'zero tolerance', 'non-volatile', 'Goldfish');
INSERT INTO Pet VALUES ('Tremaine', 'Bruhke', '2005-01-17', 'F', 'Phased', 'analyzing', 'customer loyalty', 'Rodents');
INSERT INTO Pet VALUES ('Romola', 'Tonye', '2008-10-23', 'F', '4th generation', 'Object-based', 'Function-based', 'Sheep');
INSERT INTO Pet VALUES ('Winny', 'Consuelo', '2007-05-11', 'M', 'Versatile', 'synergy', 'modular', 'Alpacas');
INSERT INTO Pet VALUES ('Belita', 'Meagan', '2007-09-26', 'F', 'Right-sized', 'dedicated', 'context-sensitive', 'Cats');
INSERT INTO Pet VALUES ('Hilarius', 'Hukins', '2009-11-17', 'M', 'asymmetric', 'Inverse', 'Devolved', 'Dogs');
INSERT INTO Pet VALUES ('Morissa', 'Muddle', '2006-03-15', 'M', 'system-worthy', 'hardware', 'modular', 'Cattle');
INSERT INTO Pet VALUES ('Winny', 'Alena', '2011-03-07', 'F', 'Business-focused', 'analyzer', 'holistic', 'Cats');
INSERT INTO Pet VALUES ('Akim', 'Isabeau', '2006-01-25', 'F', 'Customer-focused', 'software', 'fresh-thinking', 'Chinchillas');
INSERT INTO Pet VALUES ('Hildagard', 'Rossander', '2009-11-06', 'F', 'encoding', 'access', 'Advanced', 'Dogs');
INSERT INTO Pet VALUES ('Tades', 'Berridge', '2011-12-31', 'F', 'frame', 'system-worthy', 'grid-enabled', 'Koi');
INSERT INTO Pet VALUES ('Holly', 'Lochran', '2012-12-12', 'M', 'emulation', 'Ameliorated', 'Self-enabling', 'Rodents');
INSERT INTO Pet VALUES ('Belita', 'MacVanamy', '2007-06-24', 'F', 'Horizontal', 'mobile', 'zero administration', 'Mosquitofish');
INSERT INTO Pet VALUES ('Hildagard', 'Zilvia', '2002-07-25', 'M', 'Progressive', 'Face to face', 'national', 'Goldfish');
INSERT INTO Pet VALUES ('Winny', 'Ridpath', '2014-08-19', 'F', 'Sharable', 'website', 'Ergonomic', 'Rabbits');
INSERT INTO Pet VALUES ('Romola', 'Milsap', '2006-05-18', 'F', 'Synchronised', 'Optimized', 'application', 'Columbines');
INSERT INTO Pet VALUES ('Allin', 'Shalne', '2005-10-27', 'F', 'fault-tolerant', 'Switchable', 'maximized', 'Rabbits');
INSERT INTO Pet VALUES ('Hildagard', 'Mariejeanne', '2003-11-27', 'M', 'zero defect', 'projection', 'non-volatile', 'Columbines');
INSERT INTO Pet VALUES ('Gianna', 'Brundale', '2012-07-30', 'F', 'budgetary management', 'grid-enabled', 'open architecture', 'Cattle');
INSERT INTO Pet VALUES ('Holly', 'Deeann', '2008-02-23', 'F', 'fresh-thinking', 'Assimilated', 'analyzer', 'Ferrets');
INSERT INTO Pet VALUES ('Tades', 'Lynnell', '2014-06-30', 'M', 'benchmark', 'Virtual', 'utilisation', 'Sheep');
INSERT INTO Pet VALUES ('Quincey', 'Mival', '2007-09-19', 'F', 'Customizable', 'migration', 'Multi-channelled', 'Pigs');
INSERT INTO Pet VALUES ('Winny', 'Lira', '2004-06-26', 'M', '4th generation', 'interactive', 'middleware', 'Goldfish');
INSERT INTO Pet VALUES ('Akim', 'Rousby', '2011-03-16', 'M', 'composite', 'leverage', 'paradigm', 'Koi');
INSERT INTO Pet VALUES ('Allin', 'Reef', '2004-06-21', 'F', 'Grass-roots', 'migration', '6th generation', 'Hedgehogs');
INSERT INTO Pet VALUES ('Tremaine', 'McDell', '2010-06-30', 'M', 'groupware', 'didactic', 'alliance', 'Sheep');
INSERT INTO Pet VALUES ('Hilarius', 'Sutcliff', '2011-11-04', 'F', 'matrix', 'Multi-tiered', 'multi-state', 'Dogs');
INSERT INTO Pet VALUES ('Morissa', 'Coppard', '2001-05-06', 'F', 'dynamic', 'Front-line', 'superstructure', 'Horses');
INSERT INTO Pet VALUES ('Hildagard', 'Dawnay', '2003-08-15', 'F', 'monitoring', 'Team-oriented', 'eco-centric', 'Mosquitofish');
INSERT INTO Pet VALUES ('Tades', 'Drayson', '2004-03-07', 'F', 'adapter', 'capacity', 'content-based', 'Goldfish');
INSERT INTO Pet VALUES ('Holly', 'Salla', '2010-01-08', 'M', 'concept', 'support', 'bifurcated', 'Koi');
INSERT INTO Pet VALUES ('Belita', 'Loadwick', '2007-09-13', 'M', 'context-sensitive', 'local area network', 'modular', 'Goldfish');
INSERT INTO Pet VALUES ('Winny', 'Ramos', '2006-04-14', 'M', 'Face to face', 'Function-based', 'approach', 'Cats');
INSERT INTO Pet VALUES ('Romola', 'Gillhespy', '2006-06-24', 'F', 'standardization', 'national', 'open architecture', 'Koi');
INSERT INTO Pet VALUES ('Gianna', 'Lighten', '2012-05-31', 'F', 'demand-driven', 'full-range', 'Face to face', 'Cattle');
INSERT INTO Pet VALUES ('Quincey', 'Harman', '2012-03-24', 'F', 'scalable', 'Organic', 'Horizontal', 'Cattle');
INSERT INTO Pet VALUES ('Akim', 'Bapty', '2002-11-18', 'F', 'leading edge', 'exuding', 'complexity', 'Sheep');
INSERT INTO Pet VALUES ('Allin', 'Iddiens', '2000-03-27', 'M', 'circuit', 'algorithm', 'protocol', 'Ferrets');
INSERT INTO Pet VALUES ('Tremaine', 'Hucklesby', '2003-04-28', 'M', 'Cloned', 'Digitized', 'knowledge user', 'Columbines');
INSERT INTO Pet VALUES ('Hilarius', 'Rayman', '2006-01-19', 'M', 'high-level', 'user-facing', 'Total', 'Guppy');
INSERT INTO Pet VALUES ('Morissa', 'Bellham', '2012-12-19', 'M', 'software', 'web-enabled', 'Switchable', 'Hedgehogs');