INSERT INTO Pet VALUES ('Udall', 'Malinda', '2011-05-15', 'M', 'Operative 24 hour implementation', 'Total', 'software');
INSERT INTO Pet VALUES ('Weidar', 'Maris', '2007-06-10', 'F', 'Fundamental uniform data-warehouse', 'analyzer', 'Enterprise-wide');
INSERT INTO Pet VALUES ('Nils', 'Amandie', '2012-06-08', 'F', 'Enhanced reciprocal analyzer', 'access', 'customer loyalty');
INSERT INTO Pet VALUES ('Berne', 'Timmy', '2000-08-03', 'F', 'Re-contextualized radical solution', 'database', 'Robust');
INSERT INTO Pet VALUES ('Rickard', 'Harmonie', '2004-02-17', 'F', 'Secured asymmetric hardware', 'methodical', 'Decentralized');
INSERT INTO Pet VALUES ('Pascale', 'Zitella', '2015-05-15', 'F', 'Multi-tiered multimedia artificial intelligence', 'global', 'fault-tolerant');
INSERT INTO Pet VALUES ('Arel', 'Bianca', '2006-03-19', 'F', 'Mandatory even-keeled core', 'portal', 'Secured');
INSERT INTO Pet VALUES ('Reinaldos', 'Brittan', '2001-02-08', 'F', 'Persistent asymmetric project', 'Innovative', 'Programmable');
INSERT INTO Pet VALUES ('Tremaine', 'Jacquelynn', '2012-05-08', 'M', 'Persevering 5th generation hub', 'contextually-based', 'Decentralized');
INSERT INTO Pet VALUES ('Nero', 'Alla', '2012-10-26', 'F', 'Monitored object-oriented encoding', 'concept', 'budgetary management');
INSERT INTO Pet VALUES ('Harper', 'Kelsey', '2002-03-04', 'M', 'Re-engineered mission-critical orchestration', 'actuating', 'non-volatile');
INSERT INTO Pet VALUES ('Allard', 'Ketty', '2003-02-18', 'M', 'Virtual methodical parallelism', 'Vision-oriented', 'systemic');
INSERT INTO Pet VALUES ('Filbert', 'Meriel', '2000-10-06', 'M', 'Integrated object-oriented application', 'Enterprise-wide', 'didactic');
INSERT INTO Pet VALUES ('Bob', 'Dara', '2002-11-08', 'M', 'De-engineered grid-enabled array', 'open architecture', 'internet solution');
INSERT INTO Pet VALUES ('Thatcher', 'Edeline', '2013-03-01', 'F', 'Quality-focused regional alliance', 'static', 'structure');
INSERT INTO Pet VALUES ('Tanney', 'Oneida', '2010-01-10', 'F', 'Focused modular hardware', 'internet solution', 'Decentralized');
INSERT INTO Pet VALUES ('Abby', 'Carlie', '2010-07-11', 'F', 'Profound non-volatile secured line', 'Reverse-engineered', 'bifurcated');
INSERT INTO Pet VALUES ('Reamonn', 'Sophi', '2004-09-22', 'M', 'Operative multimedia framework', 'Enhanced', 'hybrid');
INSERT INTO Pet VALUES ('Antoni', 'Carlota', '2008-09-19', 'M', 'Enterprise-wide empowering software', 'Optional', 'matrix');
INSERT INTO Pet VALUES ('Carver', 'Marj', '2003-07-11', 'F', 'Versatile systemic migration', '24 hour', 'software');
INSERT INTO Pet VALUES ('Arvie', 'Camilla', '2001-12-18', 'M', 'Total bi-directional concept', 'collaboration', 'task-force');
INSERT INTO Pet VALUES ('Raynor', 'Lona', '2013-12-11', 'F', 'De-engineered cohesive help-desk', 'Optional', '24 hour');
INSERT INTO Pet VALUES ('Reinwald', 'Yalonda', '2005-05-08', 'M', 'Grass-roots executive neural-net', 'architecture', 'Self-enabling');
INSERT INTO Pet VALUES ('Nataniel', 'Cloris', '2015-06-01', 'M', 'Function-based needs-based encoding', 'Automated', 'heuristic');
INSERT INTO Pet VALUES ('Levi', 'Clarine', '2010-06-05', 'M', 'Switchable analyzing flexibility', 'info-mediaries', 'systemic');
INSERT INTO Pet VALUES ('Andras', 'Rochell', '2007-03-11', 'F', 'Enhanced zero tolerance functionalities', 'high-level', 'framework');
INSERT INTO Pet VALUES ('Berne', 'Brittney', '2012-12-04', 'F', 'Function-based bi-directional forecast', 'Fundamental', '3rd generation');
INSERT INTO Pet VALUES ('Lane', 'Enid', '2010-09-18', 'F', 'Intuitive upward-trending synergy', 'optimal', 'uniform');
INSERT INTO Pet VALUES ('Tammy', 'Angy', '2013-05-08', 'M', 'Enterprise-wide radical emulation', 'even-keeled', 'Realigned');
INSERT INTO Pet VALUES ('Fairfax', 'Rea', '2002-03-19', 'M', 'Multi-layered web-enabled matrices', 'next generation', 'monitoring');
INSERT INTO Pet VALUES ('Georgi', 'Dorie', '2004-06-12', 'F', 'Mandatory foreground database', 'intangible', 'actuating');
INSERT INTO Pet VALUES ('Evelin', 'Austin', '2002-04-18', 'M', 'Profound hybrid collaboration', 'Upgradable', 'moderator');
INSERT INTO Pet VALUES ('Trevar', 'Kettie', '2007-09-15', 'F', 'Ergonomic 3rd generation open architecture', 'Synchronised', 'Face to face');
INSERT INTO Pet VALUES ('Lorry', 'Randie', '2000-11-16', 'M', 'Managed upward-trending time-frame', 'Implemented', 'Re-engineered');
INSERT INTO Pet VALUES ('Bax', 'Claudelle', '2011-12-28', 'F', 'Multi-channelled coherent initiative', 'local area network', 'value-added');
INSERT INTO Pet VALUES ('Richart', 'Joye', '2015-07-11', 'M', 'Up-sized tangible budgetary management', 'system-worthy', 'client-driven');
INSERT INTO Pet VALUES ('Mauricio', 'Ainsley', '2014-02-23', 'M', 'De-engineered user-facing benchmark', 'homogeneous', 'solution-oriented');
INSERT INTO Pet VALUES ('Slade', 'Fayth', '2004-12-20', 'M', 'Cloned full-range toolset', 'open system', 'user-facing');
INSERT INTO Pet VALUES ('Pascale', 'Melinde', '2007-10-31', 'F', 'Innovative real-time Graphic Interface', 'focus group', 'concept');
INSERT INTO Pet VALUES ('Maurice', 'Norina', '2014-08-20', 'F', 'Programmable explicit protocol', '24 hour', 'Inverse');
INSERT INTO Pet VALUES ('Lemuel', 'Katerina', '2012-06-10', 'M', 'Cross-platform disintermediate array', 'interface', 'well-modulated');
INSERT INTO Pet VALUES ('Samuele', 'Kirsten', '2008-08-22', 'F', 'Front-line web-enabled structure', 'matrix', 'Visionary');
INSERT INTO Pet VALUES ('Alfonse', 'Oona', '2015-07-31', 'M', 'Multi-lateral human-resource interface', 'fresh-thinking', 'groupware');
INSERT INTO Pet VALUES ('Rockwell', 'Adelheid', '2008-11-14', 'F', 'Ergonomic homogeneous database', 'Optimized', 'adapter');
INSERT INTO Pet VALUES ('Vincent', 'Mickie', '2006-11-02', 'F', 'Synergistic multimedia core', 'hub', 'responsive');
INSERT INTO Pet VALUES ('Fran', 'Ruthann', '2004-03-20', 'F', 'Multi-layered executive migration', 'alliance', 'Balanced');
INSERT INTO Pet VALUES ('Humbert', 'Daffie', '2005-10-22', 'M', 'Pre-emptive didactic neural-net', 'knowledge base', 'background');
INSERT INTO Pet VALUES ('Udall', 'Carmon', '2003-07-07', 'M', 'Synchronised empowering infrastructure', 'interactive', 'project');
INSERT INTO Pet VALUES ('Carver', 'Bernie', '2002-03-10', 'M', 'Upgradable human-resource support', 'complexity', 'holistic');
INSERT INTO Pet VALUES ('Ellswerth', 'Babita', '2003-05-14', 'M', 'Synchronised even-keeled hub', 'Multi-channelled', 'customer loyalty');
INSERT INTO Pet VALUES ('Karlan', 'Deeanne', '2004-10-16', 'M', 'Switchable well-modulated moderator', 'Universal', 'Versatile');
INSERT INTO Pet VALUES ('Freeland', 'Othelia', '2009-01-03', 'F', 'Programmable 24/7 algorithm', 'toolset', 'solution');
INSERT INTO Pet VALUES ('Pepito', 'Larisa', '2003-08-01', 'M', 'User-centric didactic protocol', 'Operative', 'portal');
INSERT INTO Pet VALUES ('Janek', 'Conni', '2013-11-05', 'M', 'Expanded needs-based adapter', 'human-resource', 'Optimized');
INSERT INTO Pet VALUES ('Brig', 'Zena', '2015-08-16', 'F', 'User-centric next generation website', 'Reactive', 'protocol');
INSERT INTO Pet VALUES ('Quinlan', 'Alicia', '2006-12-02', 'F', 'Streamlined intangible monitoring', 'workforce', 'Customer-focused');
INSERT INTO Pet VALUES ('Miltie', 'Zenia', '2008-01-03', 'F', 'Self-enabling asynchronous firmware', 'Configurable', 'Optimized');
INSERT INTO Pet VALUES ('Allin', 'Tabatha', '2001-12-15', 'M', 'Cross-group mission-critical productivity', 'system engine', 'Synergistic');
INSERT INTO Pet VALUES ('Hunter', 'Mariam', '2010-06-17', 'M', 'Enterprise-wide 5th generation approach', 'Optional', 'Fundamental');
INSERT INTO Pet VALUES ('Nealson', 'Lisette', '2007-02-28', 'F', 'Team-oriented local extranet', 'monitoring', 'Centralized');
INSERT INTO Pet VALUES ('Reg', 'Gisella', '2002-04-07', 'F', 'Progressive demand-driven product', 'conglomeration', 'Realigned');
INSERT INTO Pet VALUES ('Lorry', 'Juana', '2005-04-02', 'F', 'Fully-configurable grid-enabled groupware', 'asymmetric', 'systemic');
INSERT INTO Pet VALUES ('Ulberto', 'Dulcie', '2012-01-27', 'F', 'Cross-platform user-facing focus group', 'De-engineered', 'Self-enabling');
INSERT INTO Pet VALUES ('Galvan', 'Vivyanne', '2007-04-23', 'M', 'Pre-emptive intangible time-frame', 'Digitized', 'open architecture');
INSERT INTO Pet VALUES ('Nichols', 'Janaye', '2010-02-21', 'F', 'De-engineered encompassing model', 'Upgradable', 'neural-net');
INSERT INTO Pet VALUES ('Decca', 'Lelah', '2002-12-06', 'F', 'Virtual grid-enabled pricing structure', 'upward-trending', 'foreground');
INSERT INTO Pet VALUES ('Ricki', 'Raphaela', '2002-04-25', 'M', 'Compatible zero defect application', 'Configurable', 'Ameliorated');
INSERT INTO Pet VALUES ('Cristiano', 'Alina', '2010-12-05', 'F', 'Expanded needs-based solution', 'bifurcated', 'Total');
INSERT INTO Pet VALUES ('Hurlee', 'Brandea', '2008-11-13', 'F', 'Cross-group fault-tolerant methodology', 'process improvement', 'Focused');
INSERT INTO Pet VALUES ('Palm', 'Trixi', '2000-07-30', 'M', 'Expanded holistic orchestration', 'complexity', 'multi-tasking');
INSERT INTO Pet VALUES ('Adam', 'Ronni', '2008-04-08', 'M', 'Visionary mission-critical info-mediaries', 'high-level', 'Organized');
INSERT INTO Pet VALUES ('Maddy', 'Ailyn', '2007-06-04', 'F', 'Ameliorated 6th generation functionalities', 'clear-thinking', 'bi-directional');
INSERT INTO Pet VALUES ('Waldon', 'Jolene', '2003-04-08', 'F', 'Re-contextualized maximized conglomeration', 'Synergized', 'Managed');
INSERT INTO Pet VALUES ('Angie', 'Joyann', '2007-12-15', 'F', 'Adaptive 6th generation encryption', 'analyzing', 'collaboration');
INSERT INTO Pet VALUES ('Wade', 'Henrieta', '2009-03-30', 'M', 'Ergonomic contextually-based info-mediaries', 'multi-tasking', 'approach');
INSERT INTO Pet VALUES ('Patrizius', 'Retha', '2008-05-15', 'F', 'Universal asymmetric archive', 'regional', 'productivity');
INSERT INTO Pet VALUES ('Hillyer', 'Velma', '2013-08-17', 'F', 'Profound zero administration artificial intelligence', 'benchmark', 'even-keeled');
INSERT INTO Pet VALUES ('Trevar', 'Jori', '2010-04-02', 'F', 'Monitored directional groupware', 'coherent', 'mission-critical');
INSERT INTO Pet VALUES ('Conan', 'Sharai', '2014-07-23', 'F', 'Multi-tiered tertiary matrix', 'User-friendly', 'static');
INSERT INTO Pet VALUES ('Richmond', 'Caren', '2013-01-06', 'F', 'Front-line 3rd generation collaboration', 'synergy', 'Integrated');
INSERT INTO Pet VALUES ('Nero', 'Sandye', '2014-07-02', 'F', 'Persevering zero tolerance framework', 'tertiary', 'groupware');
INSERT INTO Pet VALUES ('Caesar', 'Tommie', '2013-01-11', 'F', 'Fundamental tangible Graphic Interface', 'product', 'responsive');
INSERT INTO Pet VALUES ('Samuele', 'Peri', '2005-09-02', 'M', 'Organized bottom-line toolset', 'throughput', 'Reactive');
INSERT INTO Pet VALUES ('Harlen', 'Elsy', '2003-07-12', 'M', 'Up-sized multimedia open system', 'customer loyalty', 'hierarchy');
INSERT INTO Pet VALUES ('Darryl', 'Gilbertine', '2007-03-27', 'M', 'Multi-channelled user-facing orchestration', 'asynchronous', 'context-sensitive');
INSERT INTO Pet VALUES ('Virgil', 'Sunshine', '2009-12-02', 'M', 'Quality-focused multimedia groupware', 'multi-state', 'actuating');
INSERT INTO Pet VALUES ('Kirby', 'Lauretta', '2002-01-14', 'F', 'Vision-oriented empowering knowledge base', 'Exclusive', 'Proactive');
INSERT INTO Pet VALUES ('Oliviero', 'Faina', '2012-05-23', 'F', 'De-engineered composite complexity', 'Implemented', 'frame');
INSERT INTO Pet VALUES ('Ario', 'Zia', '2014-07-31', 'M', 'Inverse cohesive open architecture', 'secondary', 'Optimized');
INSERT INTO Pet VALUES ('Torr', 'Kylila', '2007-11-30', 'M', 'Seamless explicit superstructure', 'radical', 'dedicated');
INSERT INTO Pet VALUES ('Armando', 'Letisha', '2014-06-07', 'M', 'Realigned intangible alliance', 'executive', 'migration');
INSERT INTO Pet VALUES ('Klemens', 'Kat', '2012-11-09', 'M', 'Customizable background pricing structure', 'Polarised', 'zero administration');
INSERT INTO Pet VALUES ('Joshia', 'Anthiathia', '2013-10-19', 'F', 'Pre-emptive methodical knowledge base', 'responsive', 'workforce');
INSERT INTO Pet VALUES ('Andres', 'Anetta', '2008-09-26', 'M', 'Object-based multi-state conglomeration', 'collaboration', 'optimal');
INSERT INTO Pet VALUES ('Ellwood', 'Mandie', '2014-11-15', 'F', 'Multi-layered mission-critical collaboration', 'approach', 'groupware');
INSERT INTO Pet VALUES ('Kevin', 'Cassey', '2002-11-17', 'F', 'Profound foreground framework', 'analyzing', 'instruction set');
INSERT INTO Pet VALUES ('Weidar', 'Paolina', '2013-08-23', 'F', 'Pre-emptive transitional architecture', 'system engine', 'hierarchy');
INSERT INTO Pet VALUES ('Davie', 'Lilla', '2003-08-16', 'M', 'Horizontal systematic challenge', 'access', 'homogeneous');
INSERT INTO Pet VALUES ('Steven', 'Genna', '2008-06-13', 'M', 'Quality-focused composite database', 'database', 'regional');
INSERT INTO Pet VALUES ('Burton', 'Diena', '2012-10-25', 'F', 'Operative radical encryption', 'eco-centric', 'Inverse');
INSERT INTO Pet VALUES ('Dewitt', 'Mollee', '2008-11-06', 'F', 'Realigned object-oriented approach', 'Persevering', 'Realigned');
INSERT INTO Pet VALUES ('Cary', 'Tiphany', '2015-03-15', 'M', 'Horizontal optimizing hierarchy', 'User-friendly', 'portal');
INSERT INTO Pet VALUES ('Sasha', 'Dorolice', '2014-05-25', 'M', 'Inverse multimedia capacity', 'Organized', 'architecture');
INSERT INTO Pet VALUES ('Saxon', 'Edwina', '2012-08-17', 'F', 'Configurable national parallelism', 'Digitized', 'contextually-based');
INSERT INTO Pet VALUES ('Hillard', 'Rodina', '2013-04-12', 'F', 'Down-sized demand-driven firmware', 'Self-enabling', 'zero tolerance');
INSERT INTO Pet VALUES ('Cristiano', 'Calley', '2015-02-19', 'F', 'Centralized intermediate middleware', 'archive', 'superstructure');
INSERT INTO Pet VALUES ('Derby', 'Dacy', '2011-08-28', 'F', 'Reverse-engineered radical archive', 'model', 'empowering');
INSERT INTO Pet VALUES ('Tabby', 'Claudie', '2005-08-27', 'F', 'Intuitive multimedia pricing structure', 'Total', 'intangible');
INSERT INTO Pet VALUES ('Dannie', 'Candida', '2008-08-11', 'M', 'Innovative local budgetary management', 'multi-tasking', 'knowledge user');
INSERT INTO Pet VALUES ('Levi', 'Dagmar', '2000-06-14', 'M', 'Team-oriented 6th generation open architecture', 'encoding', 'Up-sized');
INSERT INTO Pet VALUES ('Adam', 'Cammy', '2008-08-04', 'M', 'Reverse-engineered directional groupware', 'throughput', 'projection');
INSERT INTO Pet VALUES ('Welbie', 'Mozelle', '2012-11-19', 'F', 'Sharable coherent groupware', 'tertiary', 'support');
INSERT INTO Pet VALUES ('Car', 'Tootsie', '2012-07-13', 'M', 'Balanced motivating function', 'Total', 'model');
INSERT INTO Pet VALUES ('Pascale', 'Blakeley', '2015-09-17', 'M', 'Optimized well-modulated synergy', 'Sharable', 'bifurcated');
INSERT INTO Pet VALUES ('Shannon', 'Orelee', '2007-01-10', 'F', 'Pre-emptive asymmetric emulation', 'Multi-tiered', 'contingency');
INSERT INTO Pet VALUES ('Flem', 'Adelle', '2007-02-08', 'F', 'Reactive leading edge circuit', 'Monitored', 'Graphic Interface');
INSERT INTO Pet VALUES ('Dannel', 'Vyky', '2014-11-14', 'M', 'Inverse human-resource knowledge base', 'algorithm', 'content-based');
INSERT INTO Pet VALUES ('Baron', 'Sibby', '2011-08-29', 'M', 'Distributed tangible service-desk', 'attitude-oriented', 'didactic');
INSERT INTO Pet VALUES ('Cris', 'Ruthie', '2002-03-14', 'M', 'Monitored optimal alliance', 'Horizontal', 'foreground');
INSERT INTO Pet VALUES ('Mychal', 'Dulcinea', '2002-05-31', 'M', 'Open-architected high-level paradigm', 'architecture', 'Programmable');
INSERT INTO Pet VALUES ('Rafaello', 'Eleen', '2014-06-22', 'M', 'Intuitive incremental instruction set', 'Fully-configurable', 'Customer-focused');
INSERT INTO Pet VALUES ('Zebulen', 'Billi', '2007-05-19', 'M', 'Customer-focused stable firmware', 'Devolved', 'core');
INSERT INTO Pet VALUES ('Cass', 'Natalee', '2003-02-18', 'F', 'Realigned high-level capacity', 'Decentralized', 'open system');
INSERT INTO Pet VALUES ('Olivero', 'Barbe', '2001-07-21', 'M', 'Inverse composite artificial intelligence', 'Fully-configurable', 'algorithm');
INSERT INTO Pet VALUES ('Elroy', 'Caria', '2013-02-18', 'F', 'Seamless needs-based secured line', 'disintermediate', 'regional');
INSERT INTO Pet VALUES ('Sigfrid', 'Basia', '2010-03-17', 'F', 'Phased encompassing architecture', 'modular', 'high-level');
INSERT INTO Pet VALUES ('Duffy', 'Rora', '2014-12-18', 'M', 'Robust human-resource implementation', 'Focused', 'definition');
INSERT INTO Pet VALUES ('Morten', 'Corena', '2007-09-24', 'M', 'Automated national policy', 'utilisation', 'didactic');
INSERT INTO Pet VALUES ('Rouvin', 'Dode', '2002-12-01', 'F', 'Distributed solution-oriented archive', 'instruction set', 'extranet');
INSERT INTO Pet VALUES ('Briggs', 'Nicoline', '2013-05-13', 'M', 'Optional directional approach', 'circuit', 'structure');
INSERT INTO Pet VALUES ('Kurt', 'Pooh', '2010-06-13', 'F', 'Intuitive scalable ability', 'executive', 'homogeneous');
INSERT INTO Pet VALUES ('Scotty', 'Sher', '2012-11-03', 'M', 'Switchable global algorithm', 'monitoring', 'Switchable');
INSERT INTO Pet VALUES ('Salim', 'Lishe', '2000-07-07', 'F', 'Organized tangible conglomeration', 'service-desk', 'executive');